import crypto from 'node:crypto';import fs from 'node:fs';
import {LIMITED_PRODUCTION_EXPANSION_EVIDENCE,createSyntheticAcceptedPhase59,evaluateLimitedProductionExpansionDecision,hashLimitedProductionExpansionSource,inspectLimitedProductionExpansionDecisionRegister} from '../../developer/src/agent/tutor-limited-production-expansion-decision.mjs';
const sourcePath='docs/productization/evidence/PHASE_59_LIMITED_PRODUCTION_OBSERVATION_RESULT_REGISTER.json',decisionPath='docs/productization/evidence/PHASE_60_LIMITED_PRODUCTION_EXPANSION_DECISION_REGISTER.json',contractPath='developer/contracts/ai-tutor-limited-production-expansion-decision-v1.json',outputPath='docs/productization/evidence/PHASE_60_AI_TUTOR_LIMITED_PRODUCTION_EXPANSION_DECISION_QA.json',sourceBytes=fs.readFileSync(sourcePath),decisionBytes=fs.readFileSync(decisionPath),contractBytes=fs.readFileSync(contractPath),source=JSON.parse(sourceBytes),decisionRegister=JSON.parse(decisionBytes),sourceHash=crypto.createHash('sha256').update(sourceBytes).digest('hex'),clone=(value)=>JSON.parse(JSON.stringify(value)),scenarios=[],record=(id,passed,observed)=>scenarios.push({id,passed,observed});
function acceptedPair(){const acceptedSource=createSyntheticAcceptedPhase59(source),decision=clone(decisionRegister),hash=hashLimitedProductionExpansionSource(acceptedSource);decision.source_observation.register_sha256=hash;return {acceptedSource,decision,hash};}
function verifyEvidence(decision){decision.evidence_records=LIMITED_PRODUCTION_EXPANSION_EVIDENCE.map((evidenceId,index)=>({evidence_id:evidenceId,status:'VERIFIED',evidence_reference:`SYNTHETIC-EVIDENCE-${index+1}`,verified_at:'2026-08-15T10:10:00+09:00'}));return decision;}
function approveWindow(decision){decision.decision_window={status:'APPROVED',window_reference:'SYNTHETIC-WINDOW',starts_at:'2026-08-15T10:30:00+09:00',ends_at:'2026-08-15T11:00:00+09:00',approval_inferred:false};return decision;}
{const value=evaluateLimitedProductionExpansionDecision({sourceObservationRegister:source,decisionRegister,expectedSourceHash:sourceHash});record('current-decision-blocked',value.status==='BLOCKED_EXTERNAL'&&value.evidence_verified===0,{status:value.status,blockers:value.blockers});}
{const pair=acceptedPair(),value=evaluateLimitedProductionExpansionDecision({sourceObservationRegister:pair.acceptedSource,decisionRegister:pair.decision,expectedSourceHash:pair.hash});record('accepted-source-awaits-evidence',value.status==='EXPANSION_DECISION_INCOMPLETE',{status:value.status});}
{const pair=acceptedPair();pair.decision.evidence_records.pop();pair.decision.evidence_records[1].evidence_id=pair.decision.evidence_records[0].evidence_id;const failures=inspectLimitedProductionExpansionDecisionRegister(pair.decision,{expectedSourceHash:pair.hash});record('evidence-integrity-rejected',['EVIDENCE_COUNT_MISMATCH','DUPLICATE_EVIDENCE_ID'].every((item)=>failures.includes(item)),{failures});}
{const pair=acceptedPair();verifyEvidence(pair.decision);const value=evaluateLimitedProductionExpansionDecision({sourceObservationRegister:pair.acceptedSource,decisionRegister:pair.decision,expectedSourceHash:pair.hash});record('decision-window-required',value.status==='EXPANSION_DECISION_INCOMPLETE'&&value.evidence_verified===20,{status:value.status});}
{const pair=acceptedPair();approveWindow(verifyEvidence(pair.decision));const value=evaluateLimitedProductionExpansionDecision({sourceObservationRegister:pair.acceptedSource,decisionRegister:pair.decision,expectedSourceHash:pair.hash});record('ready-for-single-review',value.status==='READY_FOR_LIMITED_PRODUCTION_EXPANSION_REVIEW',{status:value.status});}
{const pair=acceptedPair();approveWindow(verifyEvidence(pair.decision));pair.decision.review={status:'APPROVED',review_reference:'SYNTHETIC-PO',reviewed_at:'2026-08-15T10:20:00+09:00',approval_inferred:false};const value=evaluateLimitedProductionExpansionDecision({sourceObservationRegister:pair.acceptedSource,decisionRegister:pair.decision,expectedSourceHash:pair.hash});record('approval-remains-non-executing',value.status==='LIMITED_PRODUCTION_EXPANSION_HANDOFF_ACCEPTED'&&!value.expansion_authorized&&!value.student_traffic_allowed,{status:value.status});}
{const pair=acceptedPair();approveWindow(verifyEvidence(pair.decision));pair.decision.evidence_records[2]={...pair.decision.evidence_records[2],status:'REJECTED',evidence_reference:'SYNTHETIC-SAFETY-FAIL'};const value=evaluateLimitedProductionExpansionDecision({sourceObservationRegister:pair.acceptedSource,decisionRegister:pair.decision,expectedSourceHash:pair.hash});record('rejected-evidence-keeps-flag-off',value.status==='LIMITED_PRODUCTION_EXPANSION_REJECTED'&&value.recommendation==='KEEP_FEATURE_FLAG_OFF',{status:value.status});}
{const decision=clone(decisionRegister);decision.thresholds.maximum_safety_violations=1;decision.response_text='raw';decision.secret_reference='sk-exampleSecretMaterial123456';decision.expansion_executed=true;const failures=inspectLimitedProductionExpansionDecisionRegister(decision,{expectedSourceHash:'a'.repeat(64)});record('threshold-raw-secret-drift-false-expansion-rejected',['THRESHOLD_MISMATCH:maximum_safety_violations','FORBIDDEN_CONTENT_KEY:response_text','SECRET_MATERIAL_DETECTED','SOURCE_HASH_MISMATCH','EXPANSION_EXECUTED_MUST_REMAIN_FALSE'].every((item)=>failures.includes(item)),{failures});}
const passed=scenarios.filter((item)=>item.passed).length,current=evaluateLimitedProductionExpansionDecision({sourceObservationRegister:source,decisionRegister,expectedSourceHash:sourceHash}),evidence={schema_version:'1.0.0',phase:60,generated_at:new Date().toISOString(),status:passed===scenarios.length&&current.status==='BLOCKED_EXTERNAL'?'AUTO_QA_PASS_LOCAL_LIMITED_PRODUCTION_EXPANSION_DECISION_BLOCKED_EXTERNAL':'FAIL',current_decision:current,summary:{scenarios:scenarios.length,passed,failed:scenarios.length-passed},scenarios,contract_sha256:crypto.createHash('sha256').update(contractBytes).digest('hex'),source_observation_register_sha256:sourceHash,decision_register_sha256:crypto.createHash('sha256').update(decisionBytes).digest('hex'),external_actions:{api_key_accessed:false,expansion_executed:false,dispatch_performed:false,provider_live_tested:false,feature_flag_changed:false,student_traffic:false,public_traffic:false,production_promotion:false},next_authorized_action:'WAIT_FOR_ACCEPTED_PHASE59_AND_TWENTY_VERIFIED_EXPANSION_EVIDENCE_RECORDS'};fs.writeFileSync(outputPath,`${JSON.stringify(evidence,null,2)}\n`);if(evidence.status==='FAIL'){console.error('PHASE60_LIMITED_PRODUCTION_EXPANSION_DECISION_FAIL');scenarios.filter((item)=>!item.passed).forEach((item)=>console.error(item.id));process.exit(1);}console.log('PHASE60_LIMITED_PRODUCTION_EXPANSION_DECISION_PASS');console.log(`local_scenarios=${passed}/${scenarios.length}`);console.log('evidence_verified=0/20');console.log('expansion_executed=false');console.log('student_traffic=false');
