import { access, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..', '..');
const required = [
  'AGENTS.md', 'README.md', 'package.json', '.editorconfig',
  'client/README.md', 'developer/README.md', 'agent/README.md',
  'docs/client', 'docs/developer', 'docs/agent',
  'docs/productization/PHASE_ROADMAP.md', 'docs/productization/STATUS.json',
  'scripts/productization/validate_phase0.mjs'
];
const failures = [];
for (const item of required) {
  try { await access(resolve(root, item)); } catch { failures.push(`MISSING:${item}`); }
}

const agents = await readFile(resolve(root, 'AGENTS.md'), 'utf8');
for (const marker of ['수학착착', 'client/', 'developer/', 'agent/', 'ko', 'zh-CN', 'ja', 'en', 'es', 'fr', 'it', 'ru', '단위 테스트']) {
  if (!agents.includes(marker)) failures.push(`AGENTS_RULE_MISSING:${marker}`);
}

const status = JSON.parse(await readFile(resolve(root, 'docs/productization/STATUS.json'), 'utf8'));
const phaseKeys = Object.keys(status.phases || {}).map(Number).sort((a,b) => a-b);
const expectedPhaseKeys = Array.from({length:Number(status.current_phase) + 1}, (_,index) => index);
const validCurrentStatuses = new Set([
  'VERIFIED',
  'AUTO_VERIFIED_HUMAN_REVIEW_REQUIRED',
  'AUTO_VERIFIED_LOCAL_LAB',
  'AUTO_VERIFIED_LOCAL_SECURITY',
  'AUTO_VERIFIED_LOCAL_ANALYTICS',
  'AUTO_VERIFIED_LOCAL_DATA_RIGHTS',
  'AUTO_VERIFIED_LOCAL_PRIVACY_OPERATIONS',
  'AUTO_VERIFIED_LOCAL_FULFILMENT_CONTROLS',
  'AUTO_VERIFIED_LOCAL_FULFILMENT_PACKAGE',
  'AUTO_VERIFIED_LOCAL_EXECUTION_READINESS_BLOCKED_EXTERNAL',
  'AUTO_VERIFIED_LOCAL_HANDOFF_PACKET_BLOCKED_EXTERNAL',
  'AUTO_VERIFIED_LOCAL_EVIDENCE_VALIDATION_POLICY_BLOCKED_EXTERNAL',
  'AUTO_VERIFIED_LOCAL_INTAKE_ADAPTER_CONTRACT_BLOCKED_EXTERNAL',
  'AUTO_VERIFIED_LOCAL_PRE_CONNECTION_ACCEPTANCE_BLOCKED_EXTERNAL',
  'AUTO_VERIFIED_LOCAL_CONFIGURATION_EVIDENCE_QUEUE_BLOCKED_EXTERNAL',
  'AUTO_VERIFIED_LOCAL_SUBMISSION_ENVELOPE_POLICY_BLOCKED_EXTERNAL',
  'AUTO_VERIFIED_LOCAL_REFERENCE_SCHEME_GOVERNANCE_BLOCKED_EXTERNAL',
  'AUTO_VERIFIED_LOCAL_TARGET_VALIDATION_POLICY_BLOCKED_EXTERNAL',
  'AUTO_VERIFIED_LOCAL_PROOF_HANDOFF_BLOCKED_EXTERNAL',
  'AUTO_VERIFIED_LOCAL_PROOF_INTAKE_POLICY_BLOCKED_EXTERNAL',
  'AUTO_VERIFIED_LOCAL_QUARANTINE_READINESS_POLICY_BLOCKED_EXTERNAL'
  ,'AUTO_VERIFIED_LOCAL_SCANNER_READINESS_POLICY_BLOCKED_EXTERNAL'
  ,'AUTO_VERIFIED_LOCAL_SCAN_ATTESTATION_POLICY_BLOCKED_EXTERNAL'
  ,'AUTO_VERIFIED_LOCAL_RELEASE_DECISION_POLICY_BLOCKED_EXTERNAL'
  ,'AUTO_VERIFIED_LOCAL_CHAIN_CLOSED_BLOCKED_EXTERNAL'
  ,'AUTO_VERIFIED_LOCAL_P0_COMPLETE'
  ,'AUTO_VERIFIED_LOCAL_AI_TUTOR_FALLBACK_EXTERNAL_MODEL_BLOCKED'
  ,'AUTO_VERIFIED_LOCAL_AI_EVAL_HUMAN_CALIBRATION_AND_EXTERNAL_MODEL_BLOCKED'
  ,'AUTO_VERIFIED_LOCAL_AI_OPERATIONS_EXTERNAL_ENABLEMENT_BLOCKED'
  ,'AUTO_VERIFIED_LOCAL_AI_STAGING_PACKET_BLOCKED_EXTERNAL'
  ,'AUTO_VERIFIED_LOCAL_AI_CANARY_HANDOFF_BLOCKED_EXTERNAL'
  ,'AUTO_VERIFIED_LOCAL_AI_CANARY_RESULTS_BLOCKED_EXTERNAL'
  ,'AUTO_VERIFIED_LOCAL_AI_EXTENDED_STAGING_OBSERVATION_BLOCKED_EXTERNAL'
  ,'AUTO_VERIFIED_LOCAL_AI_EXTENDED_STAGING_RESULTS_BLOCKED_EXTERNAL'
  ,'AUTO_VERIFIED_LOCAL_AI_PRODUCTION_PROMOTION_HANDOFF_BLOCKED_EXTERNAL'
  ,'AUTO_VERIFIED_LOCAL_AI_CONTROLLED_PRODUCTION_ROLLOUT_BLOCKED_EXTERNAL'
  ,'AUTO_VERIFIED_LOCAL_AI_CONTROLLED_PRODUCTION_ROLLOUT_RESULTS_BLOCKED_EXTERNAL'
  ,'AUTO_VERIFIED_LOCAL_AI_LIMITED_PRODUCTION_SAFETY_HANDOFF_BLOCKED_EXTERNAL'
  ,'AUTO_VERIFIED_LOCAL_AI_LIMITED_PRODUCTION_OBSERVATION_RESULTS_BLOCKED_EXTERNAL'
  ,'AUTO_VERIFIED_LOCAL_AI_LIMITED_PRODUCTION_EXPANSION_DECISION_BLOCKED_EXTERNAL'
  ,'AUTO_VERIFIED_LOCAL_AI_LIMITED_PRODUCTION_EXPANSION_PLAN_BLOCKED_EXTERNAL'
  ,'AUTO_VERIFIED_LOCAL_AI_FINAL_PREFLIGHT_HANDOFF_BLOCKED_EXTERNAL'
  ,'AUTO_VERIFIED_LOCAL_AI_LIMITED_EXECUTION_RESULTS_BLOCKED_EXTERNAL'
  ,'AUTO_VERIFIED_LOCAL_AI_FINAL_GO_NO_GO_BLOCKED_EXTERNAL'
  ,'LOCAL_PRODUCTIZATION_CHAIN_COMPLETE_EXTERNAL_RELEASE_BLOCKED'
  ,'LOCAL_SPECIALIZATION_FOUNDATION_PASS_FIELD_EVIDENCE_BLOCKED'
  ,'LOCAL_CONTENT_CORPUS_PLATFORM_PASS_LICENSED_ITEMS_BLOCKED_EXTERNAL'
  ,'LOCAL_SOLUTION_RECOGNITION_PLATFORM_PASS_OCR_BENCHMARK_BLOCKED_EXTERNAL'
  ,'LOCAL_ACADEMY_CURRICULUM_PLATFORM_PASS_EXPERT_LICENSE_FIELD_EVIDENCE_BLOCKED'
  ,'LOCAL_TEACHER_PARENT_OPERATIONS_AUTOMATED_PASS_VISUAL_MANAGED_IDENTITY_FIELD_EVIDENCE_BLOCKED'
  ,'LOCAL_PILOT_READINESS_PLATFORM_PASS_ACTUAL_PILOT_BLOCKED_EXTERNAL'
  ,'LOCAL_MATH_EXPERT_DUAL_REVIEW_PLATFORM_PASS_ACTUAL_EXPERT_EVIDENCE_BLOCKED_EXTERNAL'
  ,'LOCAL_AI_TUTOR_EVIDENCE_PLATFORM_PASS_ACTUAL_MODEL_EVIDENCE_BLOCKED_EXTERNAL'
  ,'LOCAL_FIELD_PILOT_PLATFORM_PASS_ACTUAL_ACADEMY_EVIDENCE_BLOCKED_EXTERNAL'
  ,'LOCAL_COMMERCIAL_OPERATIONS_PLATFORM_PASS_EXTERNAL_RELEASE_BLOCKED'
]);
if (
  status.project !== 'MathChakChak' ||
  !Number.isInteger(status.current_phase) ||
  JSON.stringify(phaseKeys) !== JSON.stringify(expectedPhaseKeys) ||
  !validCurrentStatuses.has(status.phases?.[String(status.current_phase)]?.status)
) failures.push('PHASE_STATUS_INVALID');
const gate5Review = JSON.parse(await readFile(resolve(root, 'docs/stage8/evidence/2d-pet/v1.0/GATE5_AI_BEHAVIOR_MANUAL_REVIEW_v1.0.json'), 'utf8'));
const gate5Approved = gate5Review.status === 'APPROVED' && gate5Review.decision === 'APPROVE' && gate5Review.approval_applied === true;
if (gate5Approved) {
  if (status.stage8_dependency?.gate5_status !== 'VERIFIED' || status.stage8_dependency?.gate5_approval !== '1/1' || status.stage8_dependency?.gate6_entry_allowed !== true) failures.push('STAGE8_GATE_BOUNDARY_INVALID');
} else if (status.stage8_dependency?.gate5_status !== 'BLOCKED' || status.stage8_dependency?.gate5_approval !== '0/1' || status.stage8_dependency?.gate6_entry_allowed !== false) {
  failures.push('STAGE8_GATE_BOUNDARY_INVALID');
}

if (failures.length) {
  console.error('PRODUCTIZATION_PHASE0_FAIL');
  failures.forEach((failure) => console.error(failure));
  process.exit(1);
}
console.log('PRODUCTIZATION_PHASE0_PASS');
console.log(`required_paths=${required.length}/${required.length}`);
console.log('locale_rules=8/8');
console.log('stage8_gate_boundary=PASS');
