BEGIN;
DROP TABLE IF EXISTS mathchakchak.privacy_external_reference_proof_handoff_requirement;
DROP TABLE IF EXISTS mathchakchak.privacy_external_reference_proof_handoff_contract;
DROP FUNCTION IF EXISTS mathchakchak.reject_external_reference_proof_handoff_mutation();
COMMIT;
