BEGIN;
CREATE TABLE mathchakchak.privacy_external_reference_proof_scan_attestation_contract (
 id uuid PRIMARY KEY,scanner_readiness_contract_id uuid NOT NULL REFERENCES mathchakchak.privacy_external_reference_proof_scanner_readiness_contract(id) ON DELETE RESTRICT,
 package_manifest_id uuid NOT NULL REFERENCES mathchakchak.privacy_fulfilment_package_manifest(id) ON DELETE RESTRICT,revision integer NOT NULL CHECK(revision>0),
 predecessor_contract_id uuid REFERENCES mathchakchak.privacy_external_reference_proof_scan_attestation_contract(id) ON DELETE RESTRICT,
 schema_version varchar(16) NOT NULL CHECK(schema_version='1.0.0'),status varchar(64) NOT NULL CHECK(status='SCAN_ATTESTATION_POLICY_ONLY_EXTERNAL_RESULTS_MISSING'),
 contract_manifest jsonb NOT NULL,contract_sha256 char(64) NOT NULL CHECK(contract_sha256~'^[0-9a-f]{64}$'),created_by_user_id uuid NOT NULL REFERENCES mathchakchak.app_user(id) ON DELETE RESTRICT,
 kill_switch_engaged boolean NOT NULL DEFAULT true CHECK(kill_switch_engaged=true),result_intake_authorized boolean NOT NULL DEFAULT false CHECK(result_intake_authorized=false),
 attestation_validation_authorized boolean NOT NULL DEFAULT false CHECK(attestation_validation_authorized=false),release_decision_authorized boolean NOT NULL DEFAULT false CHECK(release_decision_authorized=false),execution_authorized boolean NOT NULL DEFAULT false CHECK(execution_authorized=false),created_at timestamptz NOT NULL DEFAULT now(),
 CHECK((revision=1 AND predecessor_contract_id IS NULL) OR (revision>1 AND predecessor_contract_id IS NOT NULL)),UNIQUE(scanner_readiness_contract_id,revision),UNIQUE(predecessor_contract_id));
CREATE TABLE mathchakchak.privacy_external_reference_proof_scan_attestation_requirement (
 id uuid PRIMARY KEY,attestation_contract_id uuid NOT NULL REFERENCES mathchakchak.privacy_external_reference_proof_scan_attestation_contract(id) ON DELETE RESTRICT,
 control_key varchar(48) NOT NULL,owner_role varchar(48) NOT NULL,verification_steps jsonb NOT NULL CHECK(jsonb_array_length(verification_steps)=10),result_enums jsonb NOT NULL CHECK(jsonb_array_length(result_enums)=4),reconciliation_rules jsonb NOT NULL CHECK(jsonb_array_length(reconciliation_rules)=8),failure_codes jsonb NOT NULL CHECK(jsonb_array_length(failure_codes)=12),release_guards jsonb NOT NULL CHECK(jsonb_array_length(release_guards)=10),accepted_attestations jsonb NOT NULL CHECK(accepted_attestations='[]'::jsonb),
 readiness_status varchar(56) NOT NULL CHECK(readiness_status='POLICY_DEFINED_EXTERNAL_RESULTS_MISSING'),result_status varchar(24) NOT NULL DEFAULT 'MISSING_EXTERNAL' CHECK(result_status='MISSING_EXTERNAL'),attestation_status varchar(24) NOT NULL DEFAULT 'MISSING_EXTERNAL' CHECK(attestation_status='MISSING_EXTERNAL'),reconciliation_status varchar(24) NOT NULL DEFAULT 'NOT_STARTED' CHECK(reconciliation_status='NOT_STARTED'),release_guard_status varchar(24) NOT NULL DEFAULT 'BLOCKED_EXTERNAL' CHECK(release_guard_status='BLOCKED_EXTERNAL'),metadata_only boolean NOT NULL DEFAULT true CHECK(metadata_only=true),fail_closed boolean NOT NULL DEFAULT true CHECK(fail_closed=true),dual_engine_required boolean NOT NULL DEFAULT true CHECK(dual_engine_required=true),human_release_required boolean NOT NULL DEFAULT true CHECK(human_release_required=true),raw_evidence_storage_allowed boolean NOT NULL DEFAULT false CHECK(raw_evidence_storage_allowed=false),credential_material_storage_allowed boolean NOT NULL DEFAULT false CHECK(credential_material_storage_allowed=false),secret_material_storage_allowed boolean NOT NULL DEFAULT false CHECK(secret_material_storage_allowed=false),
 object_reference varchar(191),object_sha256 char(64),primary_attestation_reference varchar(191),secondary_attestation_reference varchar(191),reconciliation_reference varchar(191),release_guard_evidence_reference varchar(191),verified_at timestamptz,reconciled_at timestamptz,
 result_intake_allowed boolean NOT NULL DEFAULT false CHECK(result_intake_allowed=false),attestation_validation_execution_allowed boolean NOT NULL DEFAULT false CHECK(attestation_validation_execution_allowed=false),result_reconciliation_allowed boolean NOT NULL DEFAULT false CHECK(result_reconciliation_allowed=false),release_guard_write_allowed boolean NOT NULL DEFAULT false CHECK(release_guard_write_allowed=false),release_decision_write_allowed boolean NOT NULL DEFAULT false CHECK(release_decision_write_allowed=false),quarantine_release_allowed boolean NOT NULL DEFAULT false CHECK(quarantine_release_allowed=false),automatic_promotion_allowed boolean NOT NULL DEFAULT false CHECK(automatic_promotion_allowed=false),
 CHECK(object_reference IS NULL AND object_sha256 IS NULL AND primary_attestation_reference IS NULL AND secondary_attestation_reference IS NULL AND reconciliation_reference IS NULL AND release_guard_evidence_reference IS NULL AND verified_at IS NULL AND reconciled_at IS NULL),UNIQUE(attestation_contract_id,control_key));
CREATE OR REPLACE FUNCTION mathchakchak.reject_proof_attestation_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'EXTERNAL_REFERENCE_PROOF_ATTESTATION_APPEND_ONLY'; END; $$;
CREATE TRIGGER proof_attestation_contract_immutable BEFORE UPDATE OR DELETE ON mathchakchak.privacy_external_reference_proof_scan_attestation_contract FOR EACH ROW EXECUTE FUNCTION mathchakchak.reject_proof_attestation_mutation();
CREATE TRIGGER proof_attestation_requirement_immutable BEFORE UPDATE OR DELETE ON mathchakchak.privacy_external_reference_proof_scan_attestation_requirement FOR EACH ROW EXECUTE FUNCTION mathchakchak.reject_proof_attestation_mutation();
CREATE INDEX proof_attestation_scanner_idx ON mathchakchak.privacy_external_reference_proof_scan_attestation_contract(scanner_readiness_contract_id,revision DESC);
COMMIT;
