BEGIN;
CREATE TABLE mathchakchak.ai_tutor_evidence_protocol(
 id uuid PRIMARY KEY,protocol_code varchar(64) NOT NULL UNIQUE,version integer NOT NULL CHECK(version>0),status varchar(32) NOT NULL CHECK(status IN('DRAFT_EXTERNAL_REVIEW','REGISTERED_LOCKED','ACTIVE','COMPLETED','SUSPENDED','CANCELLED')),protocol_sha256 char(64) NOT NULL CHECK(protocol_sha256~'^[0-9a-f]{64}$'),required_locales smallint NOT NULL DEFAULT 8 CHECK(required_locales=8),required_criteria smallint NOT NULL DEFAULT 8 CHECK(required_criteria=8),owner_identity_reference varchar(191),independent_approver_identity_reference varchar(191),registered_at timestamptz,locked_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CHECK(status='DRAFT_EXTERNAL_REVIEW' OR(owner_identity_reference IS NOT NULL AND independent_approver_identity_reference IS NOT NULL AND owner_identity_reference<>independent_approver_identity_reference AND registered_at IS NOT NULL AND locked_at IS NOT NULL)));
CREATE TABLE mathchakchak.ai_tutor_evidence_criterion(
 id uuid PRIMARY KEY,protocol_id uuid NOT NULL REFERENCES mathchakchak.ai_tutor_evidence_protocol(id) ON DELETE CASCADE,criterion_code varchar(48) NOT NULL CHECK(criterion_code IN('MATHEMATICAL_ACCURACY','EVIDENCE_GROUNDED_EXPLANATION','NO_ANSWER_REVEAL','NO_PII','SAFE_TONE','UNCERTAINTY_CALIBRATION','TEACHER_ESCALATION','LOCALE_QUALITY')),threshold_value numeric(6,4) NOT NULL CHECK(threshold_value BETWEEN 0 AND 1),threshold_direction varchar(8) NOT NULL CHECK(threshold_direction IN('MIN','MAX')),hard_gate boolean NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(protocol_id,criterion_code));
CREATE TABLE mathchakchak.ai_tutor_model_evidence_pin(
 id uuid PRIMARY KEY,protocol_id uuid NOT NULL REFERENCES mathchakchak.ai_tutor_evidence_protocol(id) ON DELETE RESTRICT,model_reference varchar(191) NOT NULL,prompt_sha256 char(64) NOT NULL CHECK(prompt_sha256~'^[0-9a-f]{64}$'),dataset_sha256 char(64) NOT NULL CHECK(dataset_sha256~'^[0-9a-f]{64}$'),dataset_version varchar(32) NOT NULL,status varchar(16) NOT NULL CHECK(status IN('PINNED','RETIRED')),pinned_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(protocol_id,model_reference,prompt_sha256,dataset_sha256),UNIQUE(id,protocol_id));
CREATE TABLE mathchakchak.ai_tutor_model_evaluation_run(
 id uuid PRIMARY KEY,protocol_id uuid NOT NULL REFERENCES mathchakchak.ai_tutor_evidence_protocol(id) ON DELETE RESTRICT,pin_id uuid NOT NULL,run_reference varchar(191) NOT NULL UNIQUE,status varchar(20) NOT NULL CHECK(status IN('STARTED','COMPLETED','REJECTED')),provider_live_tested boolean NOT NULL CHECK(provider_live_tested=true),locale_count smallint NOT NULL CHECK(locale_count=8),evaluated_case_count integer NOT NULL CHECK(evaluated_case_count>0),started_at timestamptz NOT NULL,completed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(pin_id,protocol_id) REFERENCES mathchakchak.ai_tutor_model_evidence_pin(id,protocol_id) ON DELETE RESTRICT,CHECK(status<>'COMPLETED' OR completed_at IS NOT NULL));
CREATE TABLE mathchakchak.ai_tutor_model_evaluation_summary(
 id uuid PRIMARY KEY,run_id uuid NOT NULL UNIQUE REFERENCES mathchakchak.ai_tutor_model_evaluation_run(id) ON DELETE RESTRICT,math_accuracy numeric(6,5) NOT NULL CHECK(math_accuracy BETWEEN 0 AND 1),explanation_quality numeric(6,5) NOT NULL CHECK(explanation_quality BETWEEN 0 AND 1),uncertainty_calibration numeric(6,5) NOT NULL CHECK(uncertainty_calibration BETWEEN 0 AND 1),teacher_escalation numeric(6,5) NOT NULL CHECK(teacher_escalation BETWEEN 0 AND 1),locale_quality_min numeric(6,5) NOT NULL CHECK(locale_quality_min BETWEEN 0 AND 1),safety_violations integer NOT NULL CHECK(safety_violations>=0),answer_leaks integer NOT NULL CHECK(answer_leaks>=0),pii_exposures integer NOT NULL CHECK(pii_exposures>=0),aggregate_evidence_reference varchar(191) NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE mathchakchak.ai_tutor_model_human_calibration(
 id uuid PRIMARY KEY,run_id uuid NOT NULL REFERENCES mathchakchak.ai_tutor_model_evaluation_run(id) ON DELETE RESTRICT,review_role varchar(24) NOT NULL CHECK(review_role IN('MATH_EXPERT','EDUCATION_SAFETY','INDEPENDENT_APPROVER')),reviewer_identity_reference varchar(191) NOT NULL,reviewed_case_count integer NOT NULL CHECK(reviewed_case_count>=0),agreement_rate numeric(6,5) CHECK(agreement_rate BETWEEN 0 AND 1),decision varchar(16) NOT NULL CHECK(decision IN('APPROVE','REJECT')),evidence_reference varchar(191) NOT NULL,reviewed_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(run_id,review_role,reviewer_identity_reference));
CREATE INDEX ai_tutor_evidence_criterion_protocol_idx ON mathchakchak.ai_tutor_evidence_criterion(protocol_id,criterion_code);
CREATE INDEX ai_tutor_model_run_protocol_status_idx ON mathchakchak.ai_tutor_model_evaluation_run(protocol_id,status,completed_at);
CREATE INDEX ai_tutor_human_calibration_run_role_idx ON mathchakchak.ai_tutor_model_human_calibration(run_id,review_role,decision);
CREATE OR REPLACE FUNCTION mathchakchak.prevent_ai_tutor_evidence_history_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'ai tutor evidence history is append-only' USING ERRCODE='23514'; END $$;
CREATE TRIGGER ai_tutor_pin_append_only BEFORE UPDATE OR DELETE ON mathchakchak.ai_tutor_model_evidence_pin FOR EACH ROW EXECUTE FUNCTION mathchakchak.prevent_ai_tutor_evidence_history_mutation();
CREATE TRIGGER ai_tutor_run_append_only BEFORE UPDATE OR DELETE ON mathchakchak.ai_tutor_model_evaluation_run FOR EACH ROW EXECUTE FUNCTION mathchakchak.prevent_ai_tutor_evidence_history_mutation();
CREATE TRIGGER ai_tutor_summary_append_only BEFORE UPDATE OR DELETE ON mathchakchak.ai_tutor_model_evaluation_summary FOR EACH ROW EXECUTE FUNCTION mathchakchak.prevent_ai_tutor_evidence_history_mutation();
CREATE TRIGGER ai_tutor_calibration_append_only BEFORE UPDATE OR DELETE ON mathchakchak.ai_tutor_model_human_calibration FOR EACH ROW EXECUTE FUNCTION mathchakchak.prevent_ai_tutor_evidence_history_mutation();
CREATE OR REPLACE FUNCTION mathchakchak.prevent_locked_ai_tutor_protocol_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.status IN('REGISTERED_LOCKED','ACTIVE','COMPLETED') AND(NEW.protocol_sha256 IS DISTINCT FROM OLD.protocol_sha256 OR NEW.required_locales IS DISTINCT FROM OLD.required_locales OR NEW.required_criteria IS DISTINCT FROM OLD.required_criteria OR NEW.owner_identity_reference IS DISTINCT FROM OLD.owner_identity_reference OR NEW.independent_approver_identity_reference IS DISTINCT FROM OLD.independent_approver_identity_reference OR NEW.registered_at IS DISTINCT FROM OLD.registered_at OR NEW.locked_at IS DISTINCT FROM OLD.locked_at)THEN RAISE EXCEPTION 'locked ai tutor evidence protocol is immutable' USING ERRCODE='23514';END IF;NEW.updated_at=now();RETURN NEW;END $$;
CREATE TRIGGER ai_tutor_protocol_lock_guard BEFORE UPDATE ON mathchakchak.ai_tutor_evidence_protocol FOR EACH ROW EXECUTE FUNCTION mathchakchak.prevent_locked_ai_tutor_protocol_mutation();
REVOKE ALL ON mathchakchak.ai_tutor_evidence_protocol,mathchakchak.ai_tutor_evidence_criterion,mathchakchak.ai_tutor_model_evidence_pin,mathchakchak.ai_tutor_model_evaluation_run,mathchakchak.ai_tutor_model_evaluation_summary,mathchakchak.ai_tutor_model_human_calibration FROM PUBLIC;
COMMIT;
