import {CURRICULUM_MESSAGES} from './messages.mjs?v=0.1.0-phase20';
import {STRAND_KEYS,createIdempotencyKey,groupGrades,normalizeGrade} from './model.mjs';
import {accessibilityMessage} from '../i18n/accessibility.mjs?v=0.1.0-phase21';

const supported=['ko','zh-CN','ja','en','es','fr','it','ru'];
const phaseSignals={
  1:['CONFIDENT','NEEDS_REVIEW'],
  2:['CONNECTED','NEEDS_EXAMPLE'],
  3:['DERIVED','NEEDS_GUIDANCE'],
  4:['APPLIED','NEEDS_HINT'],
  5:['VERIFIED','REVIEW_REQUIRED']
};
const runtimeMessages={
  en:{
    step:'Step {current} of 5',phasePrompt1:'Can you recall the prerequisite idea for this topic?',phasePrompt2:'Can you connect the situation or picture to the mathematical relation?',phasePrompt3:'Can you explain what the symbols mean and how the relation becomes a formula?',phasePrompt4:'Can you apply the relation while checking substitution and calculation?',phasePrompt5:'Did you check substitution, units, range, and explain the idea in your own words?',pass1:'I am ready',support1:'Review first',pass2:'I see the connection',support2:'Show an example',pass3:'I can build it',support3:'Guide me',pass4:'I applied it',support4:'I need a hint',pass5:'I verified it',support5:'Review again',complete:'Complete collaboration',score:'Collaboration evidence score: {score}% · next review in {days} day(s)',recording:'Saving progress…',recallEyebrow:'Formula recall check',recallCta:'Start quick formula check',recallTitle:'Check what you remember',recallLoading:'Loading the formula check…',recallSaving:'Checking your answer…',recallCorrect:'Correct. Recall score {score}% · review in {days} day(s).',recallIncorrect:'Review this relation once more. Recall score {score}% · review in {days} day(s).',applicationCta:'Apply the formula to problems',applicationTitle:'Formula application check',applicationStep:'Problem {current} of 3 · {kind}',applicationValue:'Answer',applicationUnit:'Unit (if requested)',applicationSubmit:'Check answer',applicationSaving:'Checking application evidence…',applicationCorrect:'Correct. Application mastery {score}% · evidence {attempted}/3.',applicationIncorrect:'Review the setup, calculation, and unit. Application mastery {score}% · evidence {attempted}/3 · {code}',applicationNext:'Next problem',applicationDone:'Three application problems recorded · review in {days} day(s).'
  },
  ko:{
    step:'5단계 중 {current}단계',phasePrompt1:'이 주제에 필요한 선수 개념이 떠오르나요?',phasePrompt2:'상황이나 그림을 수학적 관계와 연결할 수 있나요?',phasePrompt3:'기호의 뜻과 관계가 공식이 되는 과정을 설명할 수 있나요?',phasePrompt4:'값 대입과 계산을 확인하면서 관계를 적용할 수 있나요?',phasePrompt5:'대입·단위·범위를 확인하고 원리를 자신의 말로 설명했나요?',pass1:'준비됐어요',support1:'먼저 복습할래요',pass2:'관계가 보여요',support2:'예시가 필요해요',pass3:'공식을 만들 수 있어요',support3:'안내가 필요해요',pass4:'적용했어요',support4:'힌트가 필요해요',pass5:'검토했어요',support5:'다시 확인할래요',complete:'협업 학습 완료',score:'협업 진행 증거 점수 {score}% · {days}일 뒤 복습',recording:'진행을 저장하는 중…',recallEyebrow:'공식 회상 확인',recallCta:'빠른 공식 확인 시작',recallTitle:'기억한 공식을 확인해요',recallLoading:'공식 확인 문제를 불러오는 중…',recallSaving:'답을 확인하는 중…',recallCorrect:'정답입니다. 회상 점수 {score}% · {days}일 뒤 복습',recallIncorrect:'이 관계를 한 번 더 복습해 보세요. 회상 점수 {score}% · {days}일 뒤 복습',applicationCta:'실제 문제에 공식 적용하기',applicationTitle:'공식 적용 확인',applicationStep:'3문제 중 {current}번 · {kind}',applicationValue:'답',applicationUnit:'단위(문제에서 요구할 때)',applicationSubmit:'답 확인',applicationSaving:'적용 증거를 채점하는 중…',applicationCorrect:'정답입니다. 적용 숙달도 {score}% · 증거 {attempted}/3',applicationIncorrect:'식·계산·단위를 다시 확인하세요. 적용 숙달도 {score}% · 증거 {attempted}/3 · {code}',applicationNext:'다음 문제',applicationDone:'적용 문제 3개 기록 완료 · {days}일 뒤 복습'
  },
  'zh-CN':{applicationCta:'用公式解决问题',applicationTitle:'公式应用检查',applicationStep:'第 {current}/3 题 · {kind}',applicationValue:'答案',applicationUnit:'单位',applicationSubmit:'检查答案',applicationSaving:'正在检查应用证据…',applicationCorrect:'正确。应用掌握度 {score}% · 证据 {attempted}/3。',applicationIncorrect:'请重新检查列式、计算和单位。应用掌握度 {score}% · 证据 {attempted}/3 · {code}',applicationNext:'下一题',applicationDone:'已记录 3 道应用题 · {days} 天后复习'},
  ja:{applicationCta:'公式を問題に適用する',applicationTitle:'公式の応用チェック',applicationStep:'3問中{current}問 · {kind}',applicationValue:'答え',applicationUnit:'単位',applicationSubmit:'答えを確認',applicationSaving:'応用の証拠を確認中…',applicationCorrect:'正解です。応用習熟度 {score}% · 証拠 {attempted}/3。',applicationIncorrect:'式・計算・単位を確認してください。応用習熟度 {score}% · 証拠 {attempted}/3 · {code}',applicationNext:'次の問題',applicationDone:'応用問題3問を記録しました · {days}日後に復習'},
  es:{applicationCta:'Aplicar la fórmula a problemas',applicationTitle:'Comprobación de aplicación',applicationStep:'Problema {current} de 3 · {kind}',applicationValue:'Respuesta',applicationUnit:'Unidad',applicationSubmit:'Comprobar',applicationSaving:'Comprobando la evidencia…',applicationCorrect:'Correcto. Dominio de aplicación {score}% · evidencia {attempted}/3.',applicationIncorrect:'Revisa el planteamiento, el cálculo y la unidad. Dominio {score}% · evidencia {attempted}/3 · {code}',applicationNext:'Siguiente problema',applicationDone:'Tres problemas registrados · repaso en {days} días'},
  fr:{applicationCta:'Appliquer la formule',applicationTitle:'Vérification de l’application',applicationStep:'Problème {current} sur 3 · {kind}',applicationValue:'Réponse',applicationUnit:'Unité',applicationSubmit:'Vérifier',applicationSaving:'Vérification en cours…',applicationCorrect:'Correct. Maîtrise de l’application {score}% · preuves {attempted}/3.',applicationIncorrect:'Vérifie la mise en équation, le calcul et l’unité. Maîtrise {score}% · preuves {attempted}/3 · {code}',applicationNext:'Problème suivant',applicationDone:'Trois problèmes enregistrés · révision dans {days} jours'},
  it:{applicationCta:'Applicare la formula',applicationTitle:'Verifica di applicazione',applicationStep:'Problema {current} di 3 · {kind}',applicationValue:'Risposta',applicationUnit:'Unità',applicationSubmit:'Controlla',applicationSaving:'Controllo delle evidenze…',applicationCorrect:'Corretto. Padronanza applicativa {score}% · evidenze {attempted}/3.',applicationIncorrect:'Controlla impostazione, calcolo e unità. Padronanza {score}% · evidenze {attempted}/3 · {code}',applicationNext:'Problema successivo',applicationDone:'Tre problemi registrati · ripasso tra {days} giorni'},
  ru:{applicationCta:'Применить формулу',applicationTitle:'Проверка применения',applicationStep:'Задача {current} из 3 · {kind}',applicationValue:'Ответ',applicationUnit:'Единица',applicationSubmit:'Проверить',applicationSaving:'Проверяем решение…',applicationCorrect:'Верно. Уровень применения {score}% · свидетельства {attempted}/3.',applicationIncorrect:'Проверь запись, вычисление и единицу. Уровень {score}% · свидетельства {attempted}/3 · {code}',applicationNext:'Следующая задача',applicationDone:'Записаны три задачи · повторить через {days} дн.'}
};
const collaborationRuntimeMessages={
  'zh-CN':{step:'第 {current}/5 步',phasePrompt1:'你能回忆这个主题所需的先备概念吗？',phasePrompt2:'你能把情境或图示与数学关系连接起来吗？',phasePrompt3:'你能说明符号的含义以及关系如何成为公式吗？',phasePrompt4:'你能在检查代入和计算的同时应用这个关系吗？',phasePrompt5:'你检查了代入、单位和范围，并用自己的话说明原理吗？',pass1:'我准备好了',support1:'先复习',pass2:'我看到了联系',support2:'给我一个例子',pass3:'我能建立公式',support3:'请引导我',pass4:'我完成了应用',support4:'我需要提示',pass5:'我已验证',support5:'再检查一次',complete:'完成协作学习',score:'协作证据得分 {score}% · {days} 天后复习',recording:'正在保存进度…',recallEyebrow:'公式回忆检查',recallCta:'开始快速公式检查',recallTitle:'检查你记住的内容',recallLoading:'正在加载公式检查…',recallSaving:'正在检查答案…',recallCorrect:'正确。回忆得分 {score}% · {days} 天后复习。',recallIncorrect:'再复习一次这个关系。回忆得分 {score}% · {days} 天后复习。'},
  ja:{step:'5段階中 {current}段階',phasePrompt1:'このテーマに必要な前提概念を思い出せますか？',phasePrompt2:'場面や図を数学的な関係に結び付けられますか？',phasePrompt3:'記号の意味と、関係が公式になる過程を説明できますか？',phasePrompt4:'代入と計算を確認しながら関係を適用できますか？',phasePrompt5:'代入・単位・範囲を確認し、自分の言葉で原理を説明しましたか？',pass1:'準備できました',support1:'先に復習する',pass2:'つながりが分かります',support2:'例を見たい',pass3:'公式を作れます',support3:'案内が必要です',pass4:'適用できました',support4:'ヒントが必要です',pass5:'確認しました',support5:'もう一度確認する',complete:'協働学習を完了',score:'協働の証拠スコア {score}%・{days}日後に復習',recording:'進捗を保存中…',recallEyebrow:'公式の想起確認',recallCta:'短い公式確認を始める',recallTitle:'覚えている内容を確認',recallLoading:'公式確認を読み込み中…',recallSaving:'回答を確認中…',recallCorrect:'正解です。想起スコア {score}%・{days}日後に復習。',recallIncorrect:'この関係をもう一度復習しましょう。想起スコア {score}%・{days}日後に復習。'},
  es:{step:'Paso {current} de 5',phasePrompt1:'¿Recuerdas la idea previa necesaria para este tema?',phasePrompt2:'¿Puedes relacionar la situación o la imagen con la relación matemática?',phasePrompt3:'¿Puedes explicar los símbolos y cómo la relación se convierte en fórmula?',phasePrompt4:'¿Puedes aplicar la relación comprobando la sustitución y el cálculo?',phasePrompt5:'¿Comprobaste sustitución, unidades y rango, y explicaste el principio con tus palabras?',pass1:'Estoy listo',support1:'Repasar primero',pass2:'Veo la relación',support2:'Mostrar un ejemplo',pass3:'Puedo construirla',support3:'Necesito orientación',pass4:'La apliqué',support4:'Necesito una pista',pass5:'La verifiqué',support5:'Revisar otra vez',complete:'Completar la colaboración',score:'Evidencia de colaboración {score}% · repaso en {days} días',recording:'Guardando el progreso…',recallEyebrow:'Comprobación de recuerdo',recallCta:'Iniciar comprobación rápida',recallTitle:'Comprueba lo que recuerdas',recallLoading:'Cargando la comprobación…',recallSaving:'Comprobando la respuesta…',recallCorrect:'Correcto. Recuerdo {score}% · repaso en {days} días.',recallIncorrect:'Repasa esta relación una vez más. Recuerdo {score}% · repaso en {days} días.'},
  fr:{step:'Étape {current} sur 5',phasePrompt1:'Peux-tu rappeler la notion préalable nécessaire à ce thème ?',phasePrompt2:'Peux-tu relier la situation ou l’image à la relation mathématique ?',phasePrompt3:'Peux-tu expliquer les symboles et comment la relation devient une formule ?',phasePrompt4:'Peux-tu appliquer la relation en vérifiant la substitution et le calcul ?',phasePrompt5:'As-tu vérifié la substitution, les unités et le domaine, puis expliqué le principe avec tes mots ?',pass1:'Je suis prêt',support1:'Réviser d’abord',pass2:'Je vois le lien',support2:'Montrer un exemple',pass3:'Je peux la construire',support3:'J’ai besoin d’aide',pass4:'Je l’ai appliquée',support4:'J’ai besoin d’un indice',pass5:'J’ai vérifié',support5:'Vérifier encore',complete:'Terminer la collaboration',score:'Preuves de collaboration {score}% · révision dans {days} jours',recording:'Enregistrement en cours…',recallEyebrow:'Vérification du rappel',recallCta:'Commencer la vérification rapide',recallTitle:'Vérifie ce dont tu te souviens',recallLoading:'Chargement de la vérification…',recallSaving:'Vérification de la réponse…',recallCorrect:'Correct. Rappel {score}% · révision dans {days} jours.',recallIncorrect:'Révise encore cette relation. Rappel {score}% · révision dans {days} jours.'},
  it:{step:'Passaggio {current} di 5',phasePrompt1:'Ricordi il concetto preliminare necessario per questo argomento?',phasePrompt2:'Sai collegare la situazione o l’immagine alla relazione matematica?',phasePrompt3:'Sai spiegare i simboli e come la relazione diventa una formula?',phasePrompt4:'Sai applicare la relazione controllando sostituzione e calcolo?',phasePrompt5:'Hai controllato sostituzione, unità e intervallo e spiegato il principio con parole tue?',pass1:'Sono pronto',support1:'Prima ripasso',pass2:'Vedo il collegamento',support2:'Mostra un esempio',pass3:'So costruirla',support3:'Ho bisogno di guida',pass4:'L’ho applicata',support4:'Mi serve un suggerimento',pass5:'Ho verificato',support5:'Controlla di nuovo',complete:'Completa la collaborazione',score:'Evidenza di collaborazione {score}% · ripasso tra {days} giorni',recording:'Salvataggio in corso…',recallEyebrow:'Verifica del richiamo',recallCta:'Avvia la verifica rapida',recallTitle:'Controlla ciò che ricordi',recallLoading:'Caricamento della verifica…',recallSaving:'Controllo della risposta…',recallCorrect:'Corretto. Richiamo {score}% · ripasso tra {days} giorni.',recallIncorrect:'Ripassa ancora questa relazione. Richiamo {score}% · ripasso tra {days} giorni.'},
  ru:{step:'Шаг {current} из 5',phasePrompt1:'Можешь вспомнить базовую идею для этой темы?',phasePrompt2:'Можешь связать ситуацию или рисунок с математическим отношением?',phasePrompt3:'Можешь объяснить обозначения и как отношение становится формулой?',phasePrompt4:'Можешь применить отношение, проверяя подстановку и вычисление?',phasePrompt5:'Ты проверил подстановку, единицы и область и объяснил принцип своими словами?',pass1:'Я готов',support1:'Сначала повторить',pass2:'Я вижу связь',support2:'Показать пример',pass3:'Я могу построить формулу',support3:'Нужна помощь',pass4:'Я применил',support4:'Нужна подсказка',pass5:'Я проверил',support5:'Проверить ещё раз',complete:'Завершить совместное обучение',score:'Результат совместной работы {score}% · повторить через {days} дн.',recording:'Сохраняем прогресс…',recallEyebrow:'Проверка запоминания формулы',recallCta:'Начать быструю проверку',recallTitle:'Проверь, что ты запомнил',recallLoading:'Загружаем проверку…',recallSaving:'Проверяем ответ…',recallCorrect:'Верно. Запоминание {score}% · повторить через {days} дн.',recallIncorrect:'Повтори это отношение ещё раз. Запоминание {score}% · повторить через {days} дн.'}
};
const state={locale:'ko',messages:CURRICULUM_MESSAGES.ko,token:null,grades:[],gradeCode:'E1',formula:null,collaboration:null,recall:null,application:null,applicationIndex:0,activityStartedAt:0,recallStartedAt:0,applicationStartedAt:0};
const byId=(id)=>document.getElementById(id);
const elements={
  locale:byId('localeSelect'),groups:byId('gradeGroups'),summary:byId('gradeSummary'),band:byId('officialBand'),course:byId('coursePath'),count:byId('formulaCount'),grid:byId('formulaGrid'),status:byId('statusText'),panel:byId('collaborationPanel'),title:byId('collabTitle'),route:byId('routeSelect'),chakchaki:byId('chakchakiRole'),gongsickyi:byId('gongsickyiRole'),phases:byId('phaseList'),activity:byId('activityPanel'),activityStep:byId('activityStep'),activityTitle:byId('activityTitle'),activityPrompt:byId('activityPrompt'),choices:byId('signalChoices'),result:byId('activityResult'),recallPanel:byId('recallPanel'),recallTitle:byId('recallTitle'),recallPrompt:byId('recallPrompt'),recallChoices:byId('recallChoices'),recallResult:byId('recallResult'),applicationStart:byId('applicationStart'),applicationPanel:byId('applicationPanel'),applicationStep:byId('applicationStep'),applicationTitle:byId('applicationTitle'),applicationPrompt:byId('applicationPrompt'),applicationForm:byId('applicationForm'),applicationValueLabel:byId('applicationValueLabel'),applicationValue:byId('applicationValue'),applicationUnitField:byId('applicationUnitField'),applicationUnitLabel:byId('applicationUnitLabel'),applicationUnit:byId('applicationUnit'),applicationResult:byId('applicationResult'),applicationNext:byId('applicationNext')
};

function normalizeLocale(value=''){const candidate=String(value??'');const exact=supported.find((item)=>item.toLowerCase()===candidate.toLowerCase());if(exact)return exact;const language=candidate.split('-')[0].toLowerCase();return supported.find((item)=>item.split('-')[0].toLowerCase()===language)||null;}
function resolveLocale(){return normalizeLocale(new URLSearchParams(location.search).get('locale'))||normalizeLocale(navigator.language)||'ko';}
function message(key,values={}){let output=collaborationRuntimeMessages[state.locale]?.[key]??runtimeMessages[state.locale]?.[key]??state.messages[key]??CURRICULUM_MESSAGES.en[key]??runtimeMessages.en[key]??key;for(const [name,value] of Object.entries(values))output=output.replace(`{${name}}`,String(value));return output;}
function applyMessages(){document.documentElement.lang=state.locale;document.title=accessibilityMessage(state.locale,'curriculum.pageTitle');elements.locale.value=state.locale;document.querySelectorAll('[data-message]').forEach((node)=>{node.textContent=message(node.dataset.message);});document.querySelectorAll('[data-a11y-text]').forEach((node)=>{node.textContent=accessibilityMessage(state.locale,node.dataset.a11yText);});document.querySelectorAll('[data-a11y-aria]').forEach((node)=>{node.setAttribute('aria-label',accessibilityMessage(state.locale,node.dataset.a11yAria));});}
async function request(path,{method='GET',body,authenticated=true}={}){const response=await fetch(path,{method,headers:{...(authenticated&&state.token?{authorization:`Bearer ${state.token}`} : {}),...(body===undefined?{}:{'content-type':'application/json'}),...(method==='POST'&&authenticated?{'idempotency-key':createIdempotencyKey('curriculum-ui')}:{})},body:body===undefined?undefined:JSON.stringify(body)});const payload=await response.json();if(!response.ok)throw new Error(payload.error?.code||'REQUEST_FAILED');return payload.data;}
function gradeLabel(grade){return grade.label??grade.grade_code;}
function setGradeUrl(gradeCode){const url=new URL(location.href);url.searchParams.set('locale',state.locale);url.searchParams.set('grade',gradeCode);history.replaceState(null,'',url);}
function groupTitle(level){return message({ELEMENTARY:'elementary',MIDDLE:'middle',HIGH:'high'}[level]);}

function resetApplication(){state.application=null;state.applicationIndex=0;elements.applicationStart.hidden=true;elements.applicationStart.disabled=false;elements.applicationPanel.hidden=true;elements.applicationResult.hidden=true;elements.applicationNext.hidden=true;}
function resetRecall(){state.recall=null;elements.recallPanel.hidden=true;elements.recallChoices.replaceChildren();elements.recallResult.hidden=true;resetApplication();}
function renderGradeGroups(){const grouped=groupGrades(state.grades);elements.groups.replaceChildren(...Object.entries(grouped).map(([level,grades])=>{const section=document.createElement('section');section.className='grade-group';const heading=document.createElement('h2');heading.textContent=groupTitle(level);const buttons=document.createElement('div');buttons.className='grade-buttons';buttons.replaceChildren(...grades.map((grade)=>{const button=document.createElement('button');button.type='button';button.className='grade-button';button.dataset.grade=grade.grade_code;button.textContent=`${gradeLabel(grade)} · ${grade.formula_count}`;button.setAttribute('aria-current',String(grade.grade_code===state.gradeCode));button.addEventListener('click',()=>selectGrade(grade.grade_code));return button;}));section.append(heading,buttons);return section;}));}
function renderFormulas(data){const {grade,formulas}=data;elements.band.textContent=`${message('officialBand')}: ${grade.official_band} · ${message('implementation',{year:grade.implementation_year})}`;elements.course.textContent=`${message('coursePath')}: ${grade.course_path.join(' → ')}`;elements.count.textContent=message('formulaCount',{count:formulas.length});elements.summary.hidden=false;elements.grid.replaceChildren(...formulas.map((formula)=>{const article=document.createElement('article');article.className='formula-card';const tag=document.createElement('span');tag.className='tag';tag.textContent=`${message(STRAND_KEYS[formula.strand])} · ${message(`knowledge.${formula.knowledge_type}`)}`;const title=document.createElement('h2');title.textContent=formula.title;const notation=document.createElement('code');notation.textContent=formula.notation;const explanation=document.createElement('p');explanation.textContent=formula.explanation;const source=document.createElement('span');source.className='source';source.textContent=`${message('source')}: ${formula.source_citation} · ${formula.source_standard_codes.join(', ')}`;const button=document.createElement('button');button.type='button';button.textContent=message('collaboration');button.addEventListener('click',()=>openCollaboration(formula));article.append(tag,title,notation,explanation,source,button);return article;}));elements.status.textContent=message('selectFormula');}
async function selectGrade(gradeCode){state.gradeCode=normalizeGrade(gradeCode);state.formula=null;state.collaboration=null;resetRecall();elements.panel.hidden=true;elements.status.textContent=message('loading');renderGradeGroups();setGradeUrl(state.gradeCode);try{const data=await request(`/api/v1/curriculum/grades/${state.gradeCode}/formulas?locale=${encodeURIComponent(state.locale)}`);renderFormulas(data);}catch{elements.grid.replaceChildren();elements.status.textContent=message('error');}}

function renderActivity(data){const phaseNo=data.session.current_phase_no;elements.result.hidden=true;if(data.session.status==='COMPLETED'){elements.activityStep.textContent=message('together');elements.activityTitle.textContent=data.formula.title;elements.activityPrompt.textContent='';elements.result.textContent=message('score',{score:Math.round(Number(data.session.evidence_score)*100),days:data.next_review_days??'-'});elements.result.hidden=false;const recallButton=document.createElement('button');recallButton.type='button';recallButton.className='complete-choice';recallButton.textContent=message('recallCta');recallButton.addEventListener('click',openRecallCheck);elements.choices.replaceChildren(recallButton);return;}resetRecall();const phase=data.plan.phases.find((item)=>item.phase_no===phaseNo);elements.activityStep.textContent=message('step',{current:phaseNo});elements.activityTitle.textContent=phase.title;elements.activityPrompt.textContent=message(`phasePrompt${phaseNo}`);const signals=phaseSignals[phaseNo];elements.choices.replaceChildren(...signals.map((signal,index)=>{const button=document.createElement('button');button.type='button';button.className=index===0?'primary-choice':'support-choice';button.textContent=message(`${index===0?'pass':'support'}${phaseNo}`);button.addEventListener('click',()=>submitEvidence(signal,index===0?0:1));return button;}));if(data.evidence.length===5){const complete=document.createElement('button');complete.type='button';complete.className='complete-choice';complete.textContent=message('complete');complete.addEventListener('click',completeCollaboration);elements.choices.replaceChildren(complete);}state.activityStartedAt=performance.now();}
function renderCollaboration(data){state.collaboration=data;elements.title.textContent=data.formula.title;elements.chakchaki.textContent=data.plan.role_descriptions.CHAKCHAKI;elements.gongsickyi.textContent=data.plan.role_descriptions.GONGSICKYI;const completedPhases=new Set(data.evidence.map((item)=>item.phase_no));elements.phases.replaceChildren(...data.plan.phases.map((phase)=>{const item=document.createElement('li');item.className=completedPhases.has(phase.phase_no)?'is-complete':phase.phase_no===data.session.current_phase_no&&data.session.status!=='COMPLETED'?'is-current':'is-pending';const heading=document.createElement('strong');heading.textContent=phase.title;const detail=document.createElement('span');detail.textContent=phase.objective;item.append(heading,detail);return item;}));renderActivity(data);elements.panel.hidden=false;elements.panel.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
async function openCollaboration(formula){state.formula=formula;state.collaboration=null;resetRecall();elements.panel.hidden=true;elements.status.textContent=message('loading');try{const data=await request('/api/v1/curriculum/collaboration-plans',{method:'POST',body:{formula_catalog_id:formula.id,adaptive_route:elements.route.value,locale:state.locale}});renderCollaboration(data);elements.status.textContent=message('selectFormula');}catch{elements.status.textContent=message('error');}}
async function submitEvidence(signal,hintLevel){elements.choices.querySelectorAll('button').forEach((button)=>button.disabled=true);elements.activityPrompt.textContent=message('recording');try{const session=state.collaboration.session;const data=await request(`/api/v1/curriculum/collaboration-plans/${session.id}/phase-evidence`,{method:'POST',body:{phase_no:session.current_phase_no,signal,hint_level:hintLevel,duration_ms:Math.round(performance.now()-state.activityStartedAt)}});renderCollaboration(data);}catch{elements.activityPrompt.textContent=message('error');elements.choices.querySelectorAll('button').forEach((button)=>button.disabled=false);}}
async function completeCollaboration(){elements.choices.querySelectorAll('button').forEach((button)=>button.disabled=true);try{const data=await request(`/api/v1/curriculum/collaboration-plans/${state.collaboration.session.id}/complete`,{method:'POST',body:{}});renderCollaboration(data);}catch{elements.activityPrompt.textContent=message('error');}}

async function openRecallCheck(){elements.choices.querySelectorAll('button').forEach((button)=>button.disabled=true);resetApplication();elements.recallPanel.hidden=false;elements.recallTitle.textContent=message('recallTitle');elements.recallPrompt.textContent=message('recallLoading');elements.recallChoices.replaceChildren();elements.recallResult.hidden=true;try{const data=await request(`/api/v1/curriculum/formulas/${state.collaboration.formula.id}/recall-check?locale=${encodeURIComponent(state.locale)}`);state.recall=data;elements.recallPrompt.textContent=data.prompt;elements.recallChoices.replaceChildren(...data.choices.map((choice)=>{const button=document.createElement('button');button.type='button';button.textContent=choice.label;button.addEventListener('click',()=>submitRecall(choice.value));return button;}));state.recallStartedAt=performance.now();elements.recallPanel.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});}catch{elements.recallPrompt.textContent=message('error');elements.choices.querySelectorAll('button').forEach((button)=>button.disabled=false);}}
async function submitRecall(selectedValue){elements.recallChoices.querySelectorAll('button').forEach((button)=>button.disabled=true);elements.recallResult.textContent=message('recallSaving');elements.recallResult.hidden=false;try{const data=await request(`/api/v1/curriculum/recall-checks/${state.recall.id}/attempts`,{method:'POST',body:{collaboration_session_id:state.collaboration.session.id,selected_value:selectedValue,duration_ms:Math.round(performance.now()-state.recallStartedAt)}});const score=Math.round(Number(data.progress.recall_score)*100);elements.recallResult.textContent=message(data.outcome==='CORRECT'?'recallCorrect':'recallIncorrect',{score,days:data.next_review_days});elements.recallResult.dataset.outcome=data.outcome;elements.applicationStart.hidden=!state.recall.application_available;}catch{elements.recallResult.textContent=message('error');elements.recallChoices.querySelectorAll('button').forEach((button)=>button.disabled=false);}}

function renderApplicationItem(){const item=state.application.items[state.applicationIndex];elements.applicationStep.textContent=message('applicationStep',{current:state.applicationIndex+1,kind:item.assessment_kind});elements.applicationTitle.textContent=message('applicationTitle');elements.applicationPrompt.textContent=item.prompt;elements.applicationValueLabel.textContent=item.value_label;elements.applicationUnitLabel.textContent=item.unit_label;elements.applicationValue.value='';elements.applicationUnit.value='';elements.applicationUnit.required=item.unit_required;elements.applicationUnitField.hidden=!item.unit_required;elements.applicationResult.hidden=true;elements.applicationNext.hidden=true;elements.applicationForm.querySelectorAll('input,button').forEach((control)=>control.disabled=false);state.applicationStartedAt=performance.now();elements.applicationValue.focus();}
async function openApplicationChecks(){elements.applicationStart.disabled=true;elements.applicationPanel.hidden=false;elements.applicationPrompt.textContent=message('loading');try{state.application=await request(`/api/v1/curriculum/formulas/${state.collaboration.formula.id}/application-checks?locale=${encodeURIComponent(state.locale)}&collaboration_session_id=${encodeURIComponent(state.collaboration.session.id)}`);state.applicationIndex=0;renderApplicationItem();elements.applicationPanel.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});}catch{elements.applicationPrompt.textContent=message('error');elements.applicationStart.disabled=false;}}
async function submitApplication(event){event.preventDefault();elements.applicationForm.querySelectorAll('input,button').forEach((control)=>control.disabled=true);elements.applicationResult.textContent=message('applicationSaving');elements.applicationResult.hidden=false;const item=state.application.items[state.applicationIndex];try{const data=await request(`/api/v1/curriculum/application-checks/${item.id}/attempts`,{method:'POST',body:{collaboration_session_id:state.collaboration.session.id,response_value:{value:elements.applicationValue.value,unit:elements.applicationUnit.value},duration_ms:Math.round(performance.now()-state.applicationStartedAt)}});const score=Math.round(Number(data.progress.application_mastery_score)*100);elements.applicationResult.textContent=message(data.outcome==='CORRECT'?'applicationCorrect':'applicationIncorrect',{score,attempted:data.progress.attempted_items,code:data.misconception_code??'-'});elements.applicationResult.dataset.outcome=data.outcome;if(state.applicationIndex<state.application.items.length-1){elements.applicationNext.textContent=message('applicationNext');elements.applicationNext.hidden=false;}else{elements.applicationNext.hidden=true;elements.applicationResult.textContent+=` ${message('applicationDone',{days:data.next_review_days})}`;}}catch{elements.applicationResult.textContent=message('error');elements.applicationForm.querySelectorAll('input,button').forEach((control)=>control.disabled=false);}}
function nextApplicationItem(){state.applicationIndex+=1;renderApplicationItem();}

async function boot(){state.locale=resolveLocale();state.messages=CURRICULUM_MESSAGES[state.locale]||CURRICULUM_MESSAGES.en;state.gradeCode=normalizeGrade(new URLSearchParams(location.search).get('grade'));applyMessages();try{const bootstrap=await request('/api/v1/local-demo/session',{method:'POST',body:{},authenticated:false});state.token=bootstrap.access_token;const data=await request(`/api/v1/curriculum/grades?locale=${encodeURIComponent(state.locale)}`);state.grades=data.grades;if(state.grades.length!==12)throw new Error('GRADE_COUNT');renderGradeGroups();await selectGrade(state.gradeCode);}catch{elements.status.textContent=message('error');}}

elements.locale.addEventListener('change',()=>{const url=new URL(location.href);url.searchParams.set('locale',elements.locale.value);location.href=url;});
elements.route.addEventListener('change',()=>{if(state.formula)openCollaboration(state.formula);});
elements.applicationStart.addEventListener('click',openApplicationChecks);
elements.applicationForm.addEventListener('submit',submitApplication);
elements.applicationNext.addEventListener('click',nextApplicationItem);
boot();
