import {CURRICULUM_MESSAGES} from './messages.mjs';
import {STRAND_KEYS,createIdempotencyKey,groupGrades,normalizeGrade} from './model.mjs';

const supported=['ko','zh-CN','ja','en','es','fr','it','ru'];
const phaseSignals={
  1:['CONFIDENT','NEEDS_REVIEW'],
  2:['CONNECTED','NEEDS_EXAMPLE'],
  3:['DERIVED','NEEDS_GUIDANCE'],
  4:['APPLIED','NEEDS_HINT'],
  5:['VERIFIED','REVIEW_REQUIRED']
};
const runtimeMessages={
  en:{
    step:'Step {current} of 5',phasePrompt1:'Can you recall the prerequisite idea for this topic?',phasePrompt2:'Can you connect the situation or picture to the mathematical relation?',phasePrompt3:'Can you explain what the symbols mean and how the relation becomes a formula?',phasePrompt4:'Can you apply the relation while checking substitution and calculation?',phasePrompt5:'Did you check substitution, units, range, and explain the idea in your own words?',pass1:'I am ready',support1:'Review first',pass2:'I see the connection',support2:'Show an example',pass3:'I can build it',support3:'Guide me',pass4:'I applied it',support4:'I need a hint',pass5:'I verified it',support5:'Review again',complete:'Complete collaboration',score:'Collaboration evidence score: {score}% · next review in {days} day(s)',recording:'Saving progress…',recallEyebrow:'Formula recall check',recallCta:'Start quick formula check',recallTitle:'Check what you remember',recallLoading:'Loading the formula check…',recallSaving:'Checking your answer…',recallCorrect:'Correct. Recall score {score}% · review in {days} day(s).',recallIncorrect:'Review this relation once more. Recall score {score}% · review in {days} day(s).'
  },
  ko:{
    step:'5단계 중 {current}단계',phasePrompt1:'이 주제에 필요한 선수 개념이 떠오르나요?',phasePrompt2:'상황이나 그림을 수학적 관계와 연결할 수 있나요?',phasePrompt3:'기호의 뜻과 관계가 공식이 되는 과정을 설명할 수 있나요?',phasePrompt4:'값 대입과 계산을 확인하면서 관계를 적용할 수 있나요?',phasePrompt5:'대입·단위·범위를 확인하고 원리를 자신의 말로 설명했나요?',pass1:'준비됐어요',support1:'먼저 복습할래요',pass2:'관계가 보여요',support2:'예시가 필요해요',pass3:'공식을 만들 수 있어요',support3:'안내가 필요해요',pass4:'적용했어요',support4:'힌트가 필요해요',pass5:'검토했어요',support5:'다시 확인할래요',complete:'협업 학습 완료',score:'협업 진행 증거 점수 {score}% · {days}일 뒤 복습',recording:'진행을 저장하는 중…',recallEyebrow:'공식 회상 확인',recallCta:'빠른 공식 확인 시작',recallTitle:'기억한 공식을 확인해요',recallLoading:'공식 확인 문제를 불러오는 중…',recallSaving:'답을 확인하는 중…',recallCorrect:'정답입니다. 회상 점수 {score}% · {days}일 뒤 복습',recallIncorrect:'이 관계를 한 번 더 복습해 보세요. 회상 점수 {score}% · {days}일 뒤 복습'
  }
};
const state={locale:'ko',messages:CURRICULUM_MESSAGES.ko,token:null,grades:[],gradeCode:'E1',formula:null,collaboration:null,recall:null,activityStartedAt:0,recallStartedAt:0};
const byId=(id)=>document.getElementById(id);
const elements={
  locale:byId('localeSelect'),groups:byId('gradeGroups'),summary:byId('gradeSummary'),band:byId('officialBand'),course:byId('coursePath'),count:byId('formulaCount'),grid:byId('formulaGrid'),status:byId('statusText'),panel:byId('collaborationPanel'),title:byId('collabTitle'),route:byId('routeSelect'),chakchaki:byId('chakchakiRole'),gongsickyi:byId('gongsickyiRole'),phases:byId('phaseList'),activity:byId('activityPanel'),activityStep:byId('activityStep'),activityTitle:byId('activityTitle'),activityPrompt:byId('activityPrompt'),choices:byId('signalChoices'),result:byId('activityResult'),recallPanel:byId('recallPanel'),recallTitle:byId('recallTitle'),recallPrompt:byId('recallPrompt'),recallChoices:byId('recallChoices'),recallResult:byId('recallResult')
};

function normalizeLocale(value=''){const candidate=String(value??'');const exact=supported.find((item)=>item.toLowerCase()===candidate.toLowerCase());if(exact)return exact;const language=candidate.split('-')[0].toLowerCase();return supported.find((item)=>item.split('-')[0].toLowerCase()===language)||null;}
function resolveLocale(){return normalizeLocale(new URLSearchParams(location.search).get('locale'))||normalizeLocale(navigator.language)||'ko';}
function message(key,values={}){let output=runtimeMessages[state.locale]?.[key]??runtimeMessages.en[key]??state.messages[key]??CURRICULUM_MESSAGES.en[key]??key;for(const [name,value] of Object.entries(values))output=output.replace(`{${name}}`,String(value));return output;}
function applyMessages(){document.documentElement.lang=state.locale;elements.locale.value=state.locale;document.querySelectorAll('[data-message]').forEach((node)=>{node.textContent=message(node.dataset.message);});}
async function request(path,{method='GET',body,authenticated=true}={}){const response=await fetch(path,{method,headers:{...(authenticated&&state.token?{authorization:`Bearer ${state.token}`} : {}),...(body===undefined?{}:{'content-type':'application/json'}),...(method==='POST'&&authenticated?{'idempotency-key':createIdempotencyKey('curriculum-ui')}:{})},body:body===undefined?undefined:JSON.stringify(body)});const payload=await response.json();if(!response.ok)throw new Error(payload.error?.code||'REQUEST_FAILED');return payload.data;}
function gradeLabel(grade){return state.locale==='ko'?grade.label_ko:grade.grade_code;}
function setGradeUrl(gradeCode){const url=new URL(location.href);url.searchParams.set('locale',state.locale);url.searchParams.set('grade',gradeCode);history.replaceState(null,'',url);}
function groupTitle(level){return message({ELEMENTARY:'elementary',MIDDLE:'middle',HIGH:'high'}[level]);}

function resetRecall(){state.recall=null;elements.recallPanel.hidden=true;elements.recallChoices.replaceChildren();elements.recallResult.hidden=true;}
function renderGradeGroups(){const grouped=groupGrades(state.grades);elements.groups.replaceChildren(...Object.entries(grouped).map(([level,grades])=>{const section=document.createElement('section');section.className='grade-group';const heading=document.createElement('h2');heading.textContent=groupTitle(level);const buttons=document.createElement('div');buttons.className='grade-buttons';buttons.replaceChildren(...grades.map((grade)=>{const button=document.createElement('button');button.type='button';button.className='grade-button';button.dataset.grade=grade.grade_code;button.textContent=`${gradeLabel(grade)} · ${grade.formula_count}`;button.setAttribute('aria-current',String(grade.grade_code===state.gradeCode));button.addEventListener('click',()=>selectGrade(grade.grade_code));return button;}));section.append(heading,buttons);return section;}));}
function renderFormulas(data){const {grade,formulas}=data;elements.band.textContent=`${message('officialBand')}: ${grade.official_band} · ${message('implementation',{year:grade.implementation_year})}`;elements.course.textContent=`${message('coursePath')}: ${grade.course_path.join(' → ')}`;elements.count.textContent=message('formulaCount',{count:formulas.length});elements.summary.hidden=false;elements.grid.replaceChildren(...formulas.map((formula)=>{const article=document.createElement('article');article.className='formula-card';const tag=document.createElement('span');tag.className='tag';tag.textContent=`${message(STRAND_KEYS[formula.strand])} · ${formula.knowledge_type}`;const title=document.createElement('h2');title.textContent=formula.title;const notation=document.createElement('code');notation.textContent=formula.notation;const explanation=document.createElement('p');explanation.textContent=formula.explanation;const source=document.createElement('span');source.className='source';source.textContent=`${message('source')}: ${formula.notice_code} ${formula.annex} · ${formula.source_standard_codes.join(', ')}`;const button=document.createElement('button');button.type='button';button.textContent=message('collaboration');button.addEventListener('click',()=>openCollaboration(formula));article.append(tag,title,notation,explanation,source,button);return article;}));elements.status.textContent=message('selectFormula');}
async function selectGrade(gradeCode){state.gradeCode=normalizeGrade(gradeCode);state.formula=null;state.collaboration=null;resetRecall();elements.panel.hidden=true;elements.status.textContent=message('loading');renderGradeGroups();setGradeUrl(state.gradeCode);try{const data=await request(`/api/v1/curriculum/grades/${state.gradeCode}/formulas?locale=${encodeURIComponent(state.locale)}`);renderFormulas(data);}catch{elements.grid.replaceChildren();elements.status.textContent=message('error');}}

function renderActivity(data){const phaseNo=data.session.current_phase_no;elements.result.hidden=true;if(data.session.status==='COMPLETED'){elements.activityStep.textContent=message('together');elements.activityTitle.textContent=data.formula.title;elements.activityPrompt.textContent='';elements.result.textContent=message('score',{score:Math.round(Number(data.session.evidence_score)*100),days:data.next_review_days??'-'});elements.result.hidden=false;const recallButton=document.createElement('button');recallButton.type='button';recallButton.className='complete-choice';recallButton.textContent=message('recallCta');recallButton.addEventListener('click',openRecallCheck);elements.choices.replaceChildren(recallButton);return;}resetRecall();const phase=data.plan.phases.find((item)=>item.phase_no===phaseNo);elements.activityStep.textContent=message('step',{current:phaseNo});elements.activityTitle.textContent=message(`phase${phaseNo}`);elements.activityPrompt.textContent=message(`phasePrompt${phaseNo}`);const signals=phaseSignals[phaseNo];elements.choices.replaceChildren(...signals.map((signal,index)=>{const button=document.createElement('button');button.type='button';button.className=index===0?'primary-choice':'support-choice';button.textContent=message(`${index===0?'pass':'support'}${phaseNo}`);button.addEventListener('click',()=>submitEvidence(signal,index===0?0:1));return button;}));if(data.evidence.length===5){const complete=document.createElement('button');complete.type='button';complete.className='complete-choice';complete.textContent=message('complete');complete.addEventListener('click',completeCollaboration);elements.choices.replaceChildren(complete);}state.activityStartedAt=performance.now();}
function renderCollaboration(data){state.collaboration=data;elements.title.textContent=data.formula.title;elements.chakchaki.textContent=message('chakchakiRole');elements.gongsickyi.textContent=message('gongsickyiRole');const completedPhases=new Set(data.evidence.map((item)=>item.phase_no));elements.phases.replaceChildren(...data.plan.phases.map((phase)=>{const item=document.createElement('li');item.className=completedPhases.has(phase.phase_no)?'is-complete':phase.phase_no===data.session.current_phase_no&&data.session.status!=='COMPLETED'?'is-current':'is-pending';const heading=document.createElement('strong');heading.textContent=message(`phase${phase.phase_no}`);const detail=document.createElement('span');detail.textContent=phase.objective;item.append(heading,detail);return item;}));renderActivity(data);elements.panel.hidden=false;elements.panel.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
async function openCollaboration(formula){state.formula=formula;state.collaboration=null;resetRecall();elements.panel.hidden=true;elements.status.textContent=message('loading');try{const data=await request('/api/v1/curriculum/collaboration-plans',{method:'POST',body:{formula_catalog_id:formula.id,adaptive_route:elements.route.value}});renderCollaboration(data);elements.status.textContent=message('selectFormula');}catch{elements.status.textContent=message('error');}}
async function submitEvidence(signal,hintLevel){elements.choices.querySelectorAll('button').forEach((button)=>button.disabled=true);elements.activityPrompt.textContent=message('recording');try{const session=state.collaboration.session;const data=await request(`/api/v1/curriculum/collaboration-plans/${session.id}/phase-evidence`,{method:'POST',body:{phase_no:session.current_phase_no,signal,hint_level:hintLevel,duration_ms:Math.round(performance.now()-state.activityStartedAt)}});renderCollaboration(data);}catch{elements.activityPrompt.textContent=message('error');elements.choices.querySelectorAll('button').forEach((button)=>button.disabled=false);}}
async function completeCollaboration(){elements.choices.querySelectorAll('button').forEach((button)=>button.disabled=true);try{const data=await request(`/api/v1/curriculum/collaboration-plans/${state.collaboration.session.id}/complete`,{method:'POST',body:{}});renderCollaboration(data);}catch{elements.activityPrompt.textContent=message('error');}}

async function openRecallCheck(){elements.choices.querySelectorAll('button').forEach((button)=>button.disabled=true);elements.recallPanel.hidden=false;elements.recallTitle.textContent=message('recallTitle');elements.recallPrompt.textContent=message('recallLoading');elements.recallChoices.replaceChildren();elements.recallResult.hidden=true;try{const data=await request(`/api/v1/curriculum/formulas/${state.collaboration.formula.id}/recall-check?locale=${encodeURIComponent(state.locale)}`);state.recall=data;elements.recallPrompt.textContent=data.prompt;elements.recallChoices.replaceChildren(...data.choices.map((choice)=>{const button=document.createElement('button');button.type='button';button.textContent=choice.label;button.addEventListener('click',()=>submitRecall(choice.value));return button;}));state.recallStartedAt=performance.now();elements.recallPanel.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});}catch{elements.recallPrompt.textContent=message('error');elements.choices.querySelectorAll('button').forEach((button)=>button.disabled=false);}}
async function submitRecall(selectedValue){elements.recallChoices.querySelectorAll('button').forEach((button)=>button.disabled=true);elements.recallResult.textContent=message('recallSaving');elements.recallResult.hidden=false;try{const data=await request(`/api/v1/curriculum/recall-checks/${state.recall.id}/attempts`,{method:'POST',body:{collaboration_session_id:state.collaboration.session.id,selected_value:selectedValue,duration_ms:Math.round(performance.now()-state.recallStartedAt)}});const score=Math.round(Number(data.progress.recall_score)*100);elements.recallResult.textContent=message(data.outcome==='CORRECT'?'recallCorrect':'recallIncorrect',{score,days:data.next_review_days});elements.recallResult.dataset.outcome=data.outcome;}catch{elements.recallResult.textContent=message('error');elements.recallChoices.querySelectorAll('button').forEach((button)=>button.disabled=false);}}

async function boot(){state.locale=resolveLocale();state.messages=CURRICULUM_MESSAGES[state.locale]||CURRICULUM_MESSAGES.en;state.gradeCode=normalizeGrade(new URLSearchParams(location.search).get('grade'));applyMessages();try{const bootstrap=await request('/api/v1/local-demo/session',{method:'POST',body:{},authenticated:false});state.token=bootstrap.access_token;const data=await request('/api/v1/curriculum/grades');state.grades=data.grades;if(state.grades.length!==12)throw new Error('GRADE_COUNT');renderGradeGroups();await selectGrade(state.gradeCode);}catch{elements.status.textContent=message('error');}}

elements.locale.addEventListener('change',()=>{const url=new URL(location.href);url.searchParams.set('locale',elements.locale.value);location.href=url;});
elements.route.addEventListener('change',()=>{if(state.formula)openCollaboration(state.formula);});
boot();
