BEGIN;
DROP TRIGGER IF EXISTS math_expert_protocol_lock_guard ON mathchakchak.math_expert_review_protocol;
DROP TRIGGER IF EXISTS math_expert_target_status_gate ON mathchakchak.math_expert_review_target;
DROP TRIGGER IF EXISTS math_expert_resolution_gate ON mathchakchak.math_expert_disagreement_resolution;
DROP TRIGGER IF EXISTS math_expert_decision_gate ON mathchakchak.math_expert_review_decision;
DROP TRIGGER IF EXISTS math_expert_audit_append_only ON mathchakchak.math_expert_review_audit_event;
DROP TRIGGER IF EXISTS math_expert_resolution_append_only ON mathchakchak.math_expert_disagreement_resolution;
DROP TRIGGER IF EXISTS math_expert_decision_append_only ON mathchakchak.math_expert_review_decision;
DROP FUNCTION IF EXISTS mathchakchak.prevent_locked_math_expert_protocol_mutation();
DROP FUNCTION IF EXISTS mathchakchak.validate_math_expert_target_status();
DROP FUNCTION IF EXISTS mathchakchak.validate_math_expert_resolution();
DROP FUNCTION IF EXISTS mathchakchak.validate_math_expert_decision();
DROP FUNCTION IF EXISTS mathchakchak.prevent_math_expert_history_mutation();
DROP TABLE IF EXISTS mathchakchak.math_expert_review_audit_event;
DROP TABLE IF EXISTS mathchakchak.math_expert_disagreement_resolution;
DROP TABLE IF EXISTS mathchakchak.math_expert_review_decision;
DROP TABLE IF EXISTS mathchakchak.math_expert_review_assignment;
DROP TABLE IF EXISTS mathchakchak.math_expert_review_target;
DROP TABLE IF EXISTS mathchakchak.math_expert_reviewer;
DROP TABLE IF EXISTS mathchakchak.math_expert_review_criterion;
DROP TABLE IF EXISTS mathchakchak.math_expert_review_protocol;
COMMIT;
