import {createIdempotencyKey,diagnosticProgress,recommendationMessageKeys} from './model.mjs';
import {DIAGNOSTIC_MESSAGES} from './messages.mjs';

const supported=['ko','zh-CN','ja','en','es','fr','it','ru'];
const state={locale:'en',messages:DIAGNOSTIC_MESSAGES.en,token:null,items:[],index:0,diagnosticId:null,result:null,startedAt:0};
const byId=(id)=>document.getElementById(id);
const elements={locale:byId('localeSelect'),intro:byId('introPanel'),question:byId('questionPanel'),result:byId('resultPanel'),start:byId('startButton'),error:byId('errorMessage'),count:byId('questionCount'),progress:byId('progressBar'),prompt:byId('questionPrompt'),choices:byId('choiceList'),resultTitle:byId('resultTitle'),score:byId('scoreText'),description:byId('resultDescription'),learn:byId('learnButton')};

function normalizeLocale(value=''){const candidate=String(value??'');const exact=supported.find((item)=>item.toLowerCase()===candidate.toLowerCase());if(exact)return exact;const language=candidate.split('-')[0].toLowerCase();return supported.find((item)=>item.split('-')[0].toLowerCase()===language)||null;}
function resolveLocale(){return normalizeLocale(new URLSearchParams(location.search).get('locale'))||normalizeLocale(navigator.language)||'en';}
function message(key){return state.messages[key]??DIAGNOSTIC_MESSAGES.en[key]??key;}
function applyMessages(){document.documentElement.lang=state.locale;elements.locale.value=state.locale;document.querySelectorAll('[data-message]').forEach((node)=>{node.textContent=message(node.dataset.message);});}
async function request(path,{method='GET',body,authenticated=true}={}){const response=await fetch(path,{method,headers:{...(authenticated&&state.token?{authorization:`Bearer ${state.token}`} : {}),...(body===undefined?{}:{'content-type':'application/json'}),...(method==='POST'&&authenticated?{'idempotency-key':createIdempotencyKey('diagnostic-ui')}:{})},body:body===undefined?undefined:JSON.stringify(body)});const payload=await response.json();if(!response.ok)throw new Error(payload.error?.code||'REQUEST_FAILED');return payload.data;}
function fail(){elements.error.textContent=message('error');elements.error.hidden=false;elements.start.disabled=false;elements.start.textContent=message('start');}
function renderQuestion(){const item=state.items[state.index];elements.count.textContent=`${message('question')} ${state.index+1} ${message('of')} ${state.items.length}`;elements.progress.style.width=`${diagnosticProgress(state.index,state.items.length)}%`;elements.prompt.textContent=item.prompt;elements.choices.replaceChildren(...item.choices.map((choice)=>{const button=document.createElement('button');button.type='button';button.className='choice';button.textContent=choice.label;button.addEventListener('click',()=>answer(choice.value));return button;}));state.startedAt=performance.now();}
async function start(){elements.start.disabled=true;elements.start.textContent=message('loading');elements.error.hidden=true;try{const bootstrap=await request('/api/v1/local-demo/session',{method:'POST',body:{},authenticated:false});state.token=bootstrap.access_token;const [items,diagnostic]=await Promise.all([request(`/api/v1/diagnostic-items?locale=${encodeURIComponent(state.locale)}`),request('/api/v1/diagnostics',{method:'POST',body:{locale:state.locale}})]);state.items=items.items;state.diagnosticId=diagnostic.id;if(state.items.length!==3)throw new Error('DIAGNOSTIC_ITEM_COUNT');elements.intro.hidden=true;elements.question.hidden=false;renderQuestion();}catch{fail();}}
async function answer(value){elements.choices.querySelectorAll('button').forEach((button)=>button.disabled=true);try{const item=state.items[state.index];await request(`/api/v1/diagnostics/${state.diagnosticId}/responses`,{method:'POST',body:{problem_item_id:item.id,response_value:{value},duration_ms:Math.round(performance.now()-state.startedAt)}});state.index+=1;if(state.index<state.items.length){renderQuestion();return;}state.result=await request(`/api/v1/diagnostics/${state.diagnosticId}/complete`,{method:'POST',body:{}});renderResult();}catch{elements.choices.querySelectorAll('button').forEach((button)=>button.disabled=false);}}
function renderResult(){const keys=recommendationMessageKeys(state.result.recommendation.route);elements.resultTitle.textContent=message(keys.title);elements.score.textContent=message('score').replace('{correct}',String(state.result.correct));elements.description.textContent=message(keys.description);elements.question.hidden=true;elements.result.hidden=false;elements.locale.disabled=false;}
async function beginLearning(){elements.learn.disabled=true;elements.learn.textContent=message('loading');try{const handoff=await request('/api/v1/local-demo/handoffs',{method:'POST',body:{learning_path_item_id:state.result.learning_path_item_id}});location.href=`../math-learning/index.html?locale=${encodeURIComponent(state.locale)}#handoff=${handoff.code}`;}catch{elements.learn.disabled=false;elements.learn.textContent=message('learn');}}

state.locale=resolveLocale();state.messages=DIAGNOSTIC_MESSAGES[state.locale]||DIAGNOSTIC_MESSAGES.en;applyMessages();elements.start.addEventListener('click',start);elements.learn.addEventListener('click',beginLearning);elements.locale.addEventListener('change',()=>{const url=new URL(location.href);url.searchParams.set('locale',elements.locale.value);location.href=url;});
