const ko={
  'common.skip':'본문으로 건너뛰기','locale.label':'언어','auth.eyebrow':'한 번의 로그인으로 시작','auth.title':'나는 누구로 수학착착을 사용할까요?','auth.body':'역할을 먼저 선택하면 필요한 화면과 권한만 안전하게 연결합니다.','auth.trust1':'공급자 비밀번호와 토큰은 수학착착에 저장하지 않아요.','auth.trust2':'학생 정보는 보호자 또는 학원 검증 전까지 잠겨 있어요.','auth.trust3':'언제든 수학착착 세션을 로그아웃할 수 있어요.','role.title':'역할 선택','role.body':'가입 후에는 검증 없이 역할을 바꿀 수 없습니다.','role.student':'학생','role.studentHint':'내 학년의 진단과 맞춤 학습','role.parent':'학부모','role.parentHint':'연결된 자녀의 성장 확인','role.owner':'학원 원장','role.ownerHint':'학원과 교사 운영','role.teacher':'학원 교사','role.teacherHint':'배정 학생 학습 관리','provider.title':'간편 로그인','provider.body':'새 계정이면 선택한 역할로 가입 절차가 이어집니다.','provider.google':'Google로 계속','provider.naver':'네이버로 계속','provider.kakao':'카카오로 계속','provider.chooseRole':'먼저 역할을 선택해 주세요.','provider.unavailable':'현재 이 로그인 연결은 준비 중입니다.','session.title':'로그인됨','session.continue':'수학착착 시작','session.logout':'로그아웃','session.active':'계정 사용 준비가 완료되었습니다.','session.pending':'안전한 사용을 위해 추가 확인이 필요합니다.','onboarding.grade':'학년','onboarding.age':'연령 확인','onboarding.under14':'만 14세 미만 — 보호자 동의 연결','onboarding.over14':'만 14세 이상','onboarding.academyReference':'학원 인증 참조번호','onboarding.academyHint':'원장·교사는 학원 확인 전까지 학생 데이터에 접근할 수 없습니다.','onboarding.terms':'이용약관과 개인정보 처리 안내를 확인하고 동의합니다.','onboarding.submit':'가입 정보 저장','notice.failed':'요청을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.','notice.saved':'가입 정보가 안전하게 저장되었습니다.'
};
const en={
  'common.skip':'Skip to content','locale.label':'Language','auth.eyebrow':'Start with one simple sign-in','auth.title':'How will you use MathChakChak?','auth.body':'Choose a role first so we connect only the screens and permissions you need.','auth.trust1':'We do not store your provider password or provider tokens.','auth.trust2':'Student data stays locked until guardian or academy verification.','auth.trust3':'You can end your MathChakChak session at any time.','role.title':'Choose a role','role.body':'A role cannot be changed without verification after signup.','role.student':'Student','role.studentHint':'Grade-level diagnostics and learning','role.parent':'Parent','role.parentHint':'View linked child progress','role.owner':'Academy owner','role.ownerHint':'Manage academy and teachers','role.teacher':'Academy teacher','role.teacherHint':'Support assigned students','provider.title':'Quick sign-in','provider.body':'New users continue to signup with the selected role.','provider.google':'Continue with Google','provider.naver':'Continue with Naver','provider.kakao':'Continue with Kakao','provider.chooseRole':'Choose a role first.','provider.unavailable':'This sign-in connection is not configured yet.','session.title':'Signed in','session.continue':'Start MathChakChak','session.logout':'Sign out','session.active':'Your account is ready.','session.pending':'Additional verification is required for safe access.','onboarding.grade':'Grade','onboarding.age':'Age assurance','onboarding.under14':'Under 14 — connect guardian consent','onboarding.over14':'Age 14 or older','onboarding.academyReference':'Academy verification reference','onboarding.academyHint':'Owners and teachers cannot access student data before academy verification.','onboarding.terms':'I reviewed and accept the terms and privacy notice.','onboarding.submit':'Save signup details','notice.failed':'We could not complete the request. Please try again.','notice.saved':'Your signup details were saved securely.'
};
const translations={
  ko,en,
  'zh-CN':{...en,'locale.label':'语言','auth.title':'您将以什么身份使用 MathChakChak？','role.title':'选择身份','role.student':'学生','role.parent':'家长','role.owner':'培训机构负责人','role.teacher':'培训机构教师','provider.title':'快捷登录','provider.google':'使用 Google 继续','provider.naver':'使用 Naver 继续','provider.kakao':'使用 Kakao 继续','session.logout':'退出登录'},
  ja:{...en,'locale.label':'言語','auth.title':'どの立場で MathChakChak を使いますか？','role.title':'役割を選択','role.student':'生徒','role.parent':'保護者','role.owner':'塾長','role.teacher':'塾講師','provider.title':'かんたんログイン','provider.google':'Googleで続ける','provider.naver':'Naverで続ける','provider.kakao':'Kakaoで続ける','session.logout':'ログアウト'},
  es:{...en,'locale.label':'Idioma','auth.title':'¿Cómo usarás MathChakChak?','role.title':'Elige un rol','role.student':'Estudiante','role.parent':'Madre o padre','role.owner':'Director de academia','role.teacher':'Docente de academia','provider.title':'Acceso rápido','provider.google':'Continuar con Google','provider.naver':'Continuar con Naver','provider.kakao':'Continuar con Kakao','session.logout':'Cerrar sesión'},
  fr:{...en,'locale.label':'Langue','auth.title':'Comment utiliserez-vous MathChakChak ?','role.title':'Choisissez un rôle','role.student':'Élève','role.parent':'Parent','role.owner':"Directeur d'académie",'role.teacher':"Enseignant d'académie",'provider.title':'Connexion rapide','provider.google':'Continuer avec Google','provider.naver':'Continuer avec Naver','provider.kakao':'Continuer avec Kakao','session.logout':'Se déconnecter'},
  it:{...en,'locale.label':'Lingua','auth.title':'Come userai MathChakChak?','role.title':'Scegli un ruolo','role.student':'Studente','role.parent':'Genitore','role.owner':'Direttore accademia','role.teacher':'Docente accademia','provider.title':'Accesso rapido','provider.google':'Continua con Google','provider.naver':'Continua con Naver','provider.kakao':'Continua con Kakao','session.logout':'Esci'},
  ru:{...en,'locale.label':'Язык','auth.title':'Как вы будете использовать MathChakChak?','role.title':'Выберите роль','role.student':'Ученик','role.parent':'Родитель','role.owner':'Руководитель академии','role.teacher':'Преподаватель академии','provider.title':'Быстрый вход','provider.google':'Продолжить с Google','provider.naver':'Продолжить с Naver','provider.kakao':'Продолжить с Kakao','session.logout':'Выйти'}
};
export const supportedLocales=Object.freeze(['ko','zh-CN','ja','en','es','fr','it','ru']);
export const authMessages=(locale)=>translations[locale]||translations.en;
