import crypto from 'node:crypto';import fs from 'node:fs';import test from 'node:test';import assert from 'node:assert/strict';
import {createSyntheticAcceptedPhase64,evaluatePhase65,fillSyntheticPhase65Controls,hashClosureChainSource,inspectPhase65Register} from '../../../developer/src/agent/tutor-productization-closure-chain.mjs';
const sourceBytes=fs.readFileSync(new URL('../../../docs/productization/evidence/PHASE_64_FINAL_GO_NO_GO_DECISION_REGISTER.json',import.meta.url)),source=JSON.parse(sourceBytes),sourceHash=crypto.createHash('sha256').update(sourceBytes).digest('hex'),register=JSON.parse(fs.readFileSync(new URL('../../../docs/productization/evidence/PHASE_65_PRODUCTIZATION_CLOSURE_REGISTER.json',import.meta.url),'utf8')),clone=(value)=>JSON.parse(JSON.stringify(value));
function pair(){const accepted=createSyntheticAcceptedPhase64(source),closure=clone(register),hash=hashClosureChainSource(accepted);closure.source_decision.register_sha256=hash;return {accepted,closure,hash};}
test('Phase 65 is blocked with zero closure controls',()=>{const value=evaluatePhase65({sourceRegister:source,closureRegister:register,expectedSourceHash:sourceHash});assert.equal(value.status,'BLOCKED_EXTERNAL');assert.equal(value.controls_verified,0);});
test('accepted Phase 64 still waits for closure controls',()=>{const p=pair(),value=evaluatePhase65({sourceRegister:p.accepted,closureRegister:p.closure,expectedSourceHash:p.hash});assert.equal(value.status,'PRODUCTIZATION_CLOSURE_INCOMPLETE');});
test('ten verified closure controls become ready for final review',()=>{const p=pair();p.closure=fillSyntheticPhase65Controls(p.closure);const value=evaluatePhase65({sourceRegister:p.accepted,closureRegister:p.closure,expectedSourceHash:p.hash});assert.equal(value.status,'READY_FOR_PRODUCTIZATION_CLOSURE_REVIEW');});
test('single approval closes local chain without deployment or release',()=>{const p=pair();p.closure=fillSyntheticPhase65Controls(p.closure);p.closure.final_review={status:'APPROVED',review_reference:'SYNTHETIC-PO',reviewed_at:'2026-08-18T13:10:00+09:00',approval_inferred:false};const value=evaluatePhase65({sourceRegister:p.accepted,closureRegister:p.closure,expectedSourceHash:p.hash});assert.equal(value.status,'LOCAL_PRODUCTIZATION_CHAIN_COMPLETE_EXTERNAL_RELEASE_BLOCKED');assert.equal(value.local_chain_terminal,true);assert.equal(value.additional_local_phase_allowed,false);assert.equal(value.release_authorized,false);});
test('duplicate control secret source drift and false deployment fail',()=>{const p=pair();p.closure.closure_controls[1].control_id='SOURCE_GO_DECISION_ACCEPTED';p.closure.secret_reference='sk-exampleSecretMaterial123';p.closure.deployment_performed=true;const failures=inspectPhase65Register(p.closure,{expectedSourceHash:'a'.repeat(64)});for(const code of ['DUPLICATE_PHASE65_CONTROL_ID','SECRET_MATERIAL_DETECTED','PHASE65_SOURCE_HASH_MISMATCH','DEPLOYMENT_PERFORMED_MUST_REMAIN_FALSE'])assert.ok(failures.includes(code));});
