import crypto from 'node:crypto';import fs from 'node:fs';import test from 'node:test';import assert from 'node:assert/strict';import {EXPANSION_PLAN_CONTROLS,createSyntheticAcceptedPhase60,evaluateExpansionPlan,hashExpansionPlanSource,inspectExpansionPlanRegister} from '../../../developer/src/agent/tutor-limited-production-expansion-plan.mjs';
const sourceBytes=fs.readFileSync(new URL('../../../docs/productization/evidence/PHASE_60_LIMITED_PRODUCTION_EXPANSION_DECISION_REGISTER.json',import.meta.url)),source=JSON.parse(sourceBytes),sourceHash=crypto.createHash('sha256').update(sourceBytes).digest('hex'),planSource=JSON.parse(fs.readFileSync(new URL('../../../docs/productization/evidence/PHASE_61_LIMITED_PRODUCTION_EXPANSION_PLAN_REGISTER.json',import.meta.url),'utf8')),clone=(v)=>JSON.parse(JSON.stringify(v));function pair(){const acceptedSource=createSyntheticAcceptedPhase60(source),plan=clone(planSource),hash=hashExpansionPlanSource(acceptedSource);plan.source_decision.register_sha256=hash;return {acceptedSource,plan,hash};}function verify(plan){plan.control_records=EXPANSION_PLAN_CONTROLS.map((id,n)=>({control_id:id,status:'VERIFIED',evidence_reference:`SYNTHETIC-${n+1}`,verified_at:'2026-08-16T10:10:00+09:00'}));return plan;}function window(plan){plan.execution_window={status:'APPROVED',window_reference:'SYNTHETIC-WINDOW',starts_at:'2026-08-16T10:30:00+09:00',ends_at:'2026-08-16T11:30:00+09:00',approval_inferred:false};return plan;}
test('current Phase 61 remains blocked without accepted Phase 60',()=>{const v=evaluateExpansionPlan({sourceDecisionRegister:source,planRegister:planSource,expectedSourceHash:sourceHash});assert.equal(v.status,'BLOCKED_EXTERNAL');assert.equal(v.controls_verified,0);});
test('accepted source with pending controls remains incomplete',()=>{const p=pair(),v=evaluateExpansionPlan({sourceDecisionRegister:p.acceptedSource,planRegister:p.plan,expectedSourceHash:p.hash});assert.equal(v.status,'EXPANSION_PLAN_INCOMPLETE');});
test('plan has eight unique locale slots and total sixty-four requests',()=>{const f=inspectExpansionPlanRegister(planSource,{expectedSourceHash:sourceHash});assert.equal(f.length,0);assert.equal(planSource.plan_slots.length,8);assert.equal(planSource.plan_slots.reduce((s,i)=>s+i.maximum_requests,0),64);});
test('missing duplicate or expanded plan boundaries fail integrity',()=>{const p=pair();p.plan.plan_slots.pop();p.plan.plan_slots[1].locale='ko';p.plan.limits.maximum_requests=65;const f=inspectExpansionPlanRegister(p.plan,{expectedSourceHash:p.hash});assert.ok(f.includes('PLAN_SLOT_COUNT_MISMATCH'));assert.ok(f.includes('DUPLICATE_SLOT_LOCALE'));assert.ok(f.includes('LIMIT_MISMATCH:maximum_requests'));});
test('verified controls and window become ready for single review',()=>{const p=pair();window(verify(p.plan));const v=evaluateExpansionPlan({sourceDecisionRegister:p.acceptedSource,planRegister:p.plan,expectedSourceHash:p.hash});assert.equal(v.status,'READY_FOR_EXPANSION_PLAN_REVIEW');});
test('single approval creates only a non-dispatching execution handoff',()=>{const p=pair();window(verify(p.plan));p.plan.review={status:'APPROVED',review_reference:'SYNTHETIC-PO',reviewed_at:'2026-08-16T10:20:00+09:00',approval_inferred:false};const v=evaluateExpansionPlan({sourceDecisionRegister:p.acceptedSource,planRegister:p.plan,expectedSourceHash:p.hash});assert.equal(v.status,'EXPANSION_PLAN_ACCEPTED_FOR_EXECUTION_HANDOFF');assert.equal(v.execution_authorized,false);assert.equal(v.dispatch_allowed,false);});
test('one rejected control keeps feature flag off',()=>{const p=pair();window(verify(p.plan));p.plan.control_records[5]={...p.plan.control_records[5],status:'REJECTED',evidence_reference:'RAW-STORAGE-FAIL'};const v=evaluateExpansionPlan({sourceDecisionRegister:p.acceptedSource,planRegister:p.plan,expectedSourceHash:p.hash});assert.equal(v.status,'EXPANSION_PLAN_REJECTED');assert.equal(v.recommendation,'KEEP_FEATURE_FLAG_OFF');});
test('raw secret source drift false execution and overlong window are rejected',()=>{const p=pair();p.plan.response_text='raw';p.plan.secret_reference='sk-exampleSecretMaterial123456';p.plan.plan_executed=true;p.plan.execution_window={status:'APPROVED',window_reference:'WINDOW',starts_at:'2026-08-16T10:00:00+09:00',ends_at:'2026-08-16T11:01:00+09:00',approval_inferred:false};const f=inspectExpansionPlanRegister(p.plan,{expectedSourceHash:'a'.repeat(64)});assert.ok(f.includes('FORBIDDEN_CONTENT_KEY:response_text'));assert.ok(f.includes('SECRET_MATERIAL_DETECTED'));assert.ok(f.includes('SOURCE_HASH_MISMATCH'));assert.ok(f.includes('PLAN_EXECUTED_MUST_REMAIN_FALSE'));assert.ok(f.includes('EXECUTION_WINDOW_EVIDENCE_REQUIRED'));});
