import crypto from 'node:crypto';import fs from 'node:fs';import test from 'node:test';import assert from 'node:assert/strict';
import {createSyntheticAcceptedPhase63,evaluatePhase64,fillSyntheticPhase64Evidence,hashClosureChainSource,inspectPhase64Register} from '../../../developer/src/agent/tutor-productization-closure-chain.mjs';
const sourceBytes=fs.readFileSync(new URL('../../../docs/productization/evidence/PHASE_63_LIMITED_EXECUTION_RESULT_REGISTER.json',import.meta.url)),source=JSON.parse(sourceBytes),sourceHash=crypto.createHash('sha256').update(sourceBytes).digest('hex'),register=JSON.parse(fs.readFileSync(new URL('../../../docs/productization/evidence/PHASE_64_FINAL_GO_NO_GO_DECISION_REGISTER.json',import.meta.url),'utf8')),clone=(value)=>JSON.parse(JSON.stringify(value));
function pair(){const accepted=createSyntheticAcceptedPhase63(source),decision=clone(register),hash=hashClosureChainSource(accepted);decision.source_results.register_sha256=hash;return {accepted,decision,hash};}
test('Phase 64 is blocked with zero final evidence',()=>{const value=evaluatePhase64({sourceRegister:source,decisionRegister:register,expectedSourceHash:sourceHash});assert.equal(value.status,'BLOCKED_EXTERNAL');assert.equal(value.evidence_verified,0);});
test('accepted Phase 63 still waits for composite evidence',()=>{const p=pair(),value=evaluatePhase64({sourceRegister:p.accepted,decisionRegister:p.decision,expectedSourceHash:p.hash});assert.equal(value.status,'FINAL_GO_NO_GO_INCOMPLETE');});
test('twelve verified evidence records and window become ready for review',()=>{const p=pair();p.decision=fillSyntheticPhase64Evidence(p.decision);const value=evaluatePhase64({sourceRegister:p.accepted,decisionRegister:p.decision,expectedSourceHash:p.hash});assert.equal(value.status,'READY_FOR_FINAL_GO_NO_GO_REVIEW');});
test('single approval creates only manual release handoff',()=>{const p=pair();p.decision=fillSyntheticPhase64Evidence(p.decision);p.decision.review={status:'APPROVED',review_reference:'SYNTHETIC-PO',reviewed_at:'2026-08-18T12:20:00+09:00',approval_inferred:false};const value=evaluatePhase64({sourceRegister:p.accepted,decisionRegister:p.decision,expectedSourceHash:p.hash});assert.equal(value.status,'PRODUCTION_GO_DECISION_ACCEPTED_FOR_MANUAL_RELEASE');assert.equal(value.release_authorized,false);});
test('threshold relaxation secret source drift and false release fail',()=>{const p=pair();p.decision.thresholds.quality_success_rate_min=0.9;p.decision.secret_reference='sk-exampleSecretMaterial123';p.decision.release_executed=true;const failures=inspectPhase64Register(p.decision,{expectedSourceHash:'a'.repeat(64)});for(const code of ['PHASE64_THRESHOLD_MISMATCH:quality_success_rate_min','SECRET_MATERIAL_DETECTED','PHASE64_SOURCE_HASH_MISMATCH','RELEASE_EXECUTED_MUST_REMAIN_FALSE'])assert.ok(failures.includes(code));});
