import crypto from 'node:crypto';import fs from 'node:fs';import test from 'node:test';import assert from 'node:assert/strict';
import {LIMITED_PRODUCTION_EXPANSION_EVIDENCE,createSyntheticAcceptedPhase59,evaluateLimitedProductionExpansionDecision,hashLimitedProductionExpansionSource,inspectLimitedProductionExpansionDecisionRegister} from '../../../developer/src/agent/tutor-limited-production-expansion-decision.mjs';
const sourceBytes=fs.readFileSync(new URL('../../../docs/productization/evidence/PHASE_59_LIMITED_PRODUCTION_OBSERVATION_RESULT_REGISTER.json',import.meta.url)),source=JSON.parse(sourceBytes),sourceHash=crypto.createHash('sha256').update(sourceBytes).digest('hex'),decisionSource=JSON.parse(fs.readFileSync(new URL('../../../docs/productization/evidence/PHASE_60_LIMITED_PRODUCTION_EXPANSION_DECISION_REGISTER.json',import.meta.url),'utf8')),clone=(value)=>JSON.parse(JSON.stringify(value));
function acceptedPair(){const acceptedSource=createSyntheticAcceptedPhase59(source),decision=clone(decisionSource),hash=hashLimitedProductionExpansionSource(acceptedSource);decision.source_observation.register_sha256=hash;return {acceptedSource,decision,hash};}
function verifyEvidence(decision){decision.evidence_records=LIMITED_PRODUCTION_EXPANSION_EVIDENCE.map((evidenceId,index)=>({evidence_id:evidenceId,status:'VERIFIED',evidence_reference:`SYNTHETIC-EVIDENCE-${index+1}`,verified_at:'2026-08-15T10:10:00+09:00'}));return decision;}
function approveWindow(decision){decision.decision_window={status:'APPROVED',window_reference:'SYNTHETIC-DECISION-WINDOW',starts_at:'2026-08-15T10:30:00+09:00',ends_at:'2026-08-15T11:00:00+09:00',approval_inferred:false};return decision;}
test('current Phase 60 remains blocked without accepted Phase 59 evidence',()=>{const value=evaluateLimitedProductionExpansionDecision({sourceObservationRegister:source,decisionRegister:decisionSource,expectedSourceHash:sourceHash});assert.equal(value.status,'BLOCKED_EXTERNAL');assert.equal(value.evidence_verified,0);assert.equal(value.expansion_authorized,false);});
test('accepted Phase 59 with pending evidence remains incomplete',()=>{const pair=acceptedPair(),value=evaluateLimitedProductionExpansionDecision({sourceObservationRegister:pair.acceptedSource,decisionRegister:pair.decision,expectedSourceHash:pair.hash});assert.equal(value.status,'EXPANSION_DECISION_INCOMPLETE');assert.ok(value.blockers.includes('EXPANSION_EVIDENCE_INCOMPLETE'));});
test('missing and duplicate evidence fail integrity',()=>{const pair=acceptedPair();pair.decision.evidence_records.pop();pair.decision.evidence_records[1].evidence_id=pair.decision.evidence_records[0].evidence_id;const failures=inspectLimitedProductionExpansionDecisionRegister(pair.decision,{expectedSourceHash:pair.hash});assert.ok(failures.includes('EVIDENCE_COUNT_MISMATCH'));assert.ok(failures.includes('DUPLICATE_EVIDENCE_ID'));});
test('all evidence without a decision window remains incomplete',()=>{const pair=acceptedPair();verifyEvidence(pair.decision);const value=evaluateLimitedProductionExpansionDecision({sourceObservationRegister:pair.acceptedSource,decisionRegister:pair.decision,expectedSourceHash:pair.hash});assert.equal(value.status,'EXPANSION_DECISION_INCOMPLETE');assert.equal(value.evidence_verified,20);});
test('all evidence and window become ready for single review',()=>{const pair=acceptedPair();approveWindow(verifyEvidence(pair.decision));const value=evaluateLimitedProductionExpansionDecision({sourceObservationRegister:pair.acceptedSource,decisionRegister:pair.decision,expectedSourceHash:pair.hash});assert.equal(value.status,'READY_FOR_LIMITED_PRODUCTION_EXPANSION_REVIEW');assert.equal(value.recommendation,'REQUEST_PRODUCT_OWNER_REVIEW');});
test('single approval accepts only a non-executing expansion plan handoff',()=>{const pair=acceptedPair();approveWindow(verifyEvidence(pair.decision));pair.decision.review={status:'APPROVED',review_reference:'SYNTHETIC-PO',reviewed_at:'2026-08-15T10:20:00+09:00',approval_inferred:false};const value=evaluateLimitedProductionExpansionDecision({sourceObservationRegister:pair.acceptedSource,decisionRegister:pair.decision,expectedSourceHash:pair.hash});assert.equal(value.status,'LIMITED_PRODUCTION_EXPANSION_HANDOFF_ACCEPTED');assert.equal(value.expansion_authorized,false);assert.equal(value.student_traffic_allowed,false);});
test('one rejected evidence keeps feature flag off',()=>{const pair=acceptedPair();approveWindow(verifyEvidence(pair.decision));pair.decision.evidence_records[2]={...pair.decision.evidence_records[2],status:'REJECTED',evidence_reference:'SYNTHETIC-SAFETY-FAIL'};const value=evaluateLimitedProductionExpansionDecision({sourceObservationRegister:pair.acceptedSource,decisionRegister:pair.decision,expectedSourceHash:pair.hash});assert.equal(value.status,'LIMITED_PRODUCTION_EXPANSION_REJECTED');assert.equal(value.recommendation,'KEEP_FEATURE_FLAG_OFF');});
test('threshold relaxation raw secret source drift and false expansion are rejected',()=>{const decision=clone(decisionSource);decision.thresholds.maximum_safety_violations=1;decision.response_text='raw';decision.secret_reference='sk-exampleSecretMaterial123456';decision.expansion_executed=true;const failures=inspectLimitedProductionExpansionDecisionRegister(decision,{expectedSourceHash:'a'.repeat(64)});assert.ok(failures.includes('THRESHOLD_MISMATCH:maximum_safety_violations'));assert.ok(failures.includes('FORBIDDEN_CONTENT_KEY:response_text'));assert.ok(failures.includes('SECRET_MATERIAL_DETECTED'));assert.ok(failures.includes('SOURCE_HASH_MISMATCH'));assert.ok(failures.includes('EXPANSION_EXECUTED_MUST_REMAIN_FALSE'));});
