import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {hashCanonical} from '../../developer/src/privacy/fulfilment-package.mjs';

const baseUrl=process.env.API_BASE_URL||'http://127.0.0.1:4181';
const key=(label)=>`phase41-${label}-${crypto.randomUUID()}`;
const post=async(path,authorization,label,body={})=>{
  const response=await fetch(`${baseUrl}${path}`,{
    method:'POST',headers:{authorization,'content-type':'application/json','idempotency-key':key(label)},body:JSON.stringify(body)
  });
  return {response,payload:await response.json()};
};

test('quarantine readiness defines storage and inspection policy without uploading or scanning content',async()=>{
  const studentIssued=await post('/api/v1/local-demo/session','','student-session');
  const studentAuth=`Bearer ${studentIssued.payload.data.access_token}`;
  const request=await post('/api/v1/privacy/requests',studentAuth,'request',{request_type:'EXPORT',locale:'ko'});
  assert.equal(request.response.status,201);
  const requestId=request.payload.data.id;
  const operatorIssued=await post('/api/v1/local-demo/privacy-operator/session','','operator-session');
  const operatorAuth=`Bearer ${operatorIssued.payload.data.access_token}`;
  const transition=(to_status,body={})=>post(`/api/v1/privacy-operations/requests/${requestId}/transition`,operatorAuth,to_status,{to_status,...body});
  assert.equal((await transition('IDENTITY_VERIFIED',{evidence_reference:'LOCAL-EVIDENCE/phase41-identity',evidence_sha256:'d'.repeat(64)})).response.status,200);
  assert.equal((await transition('IN_REVIEW')).response.status,200);
  assert.equal((await transition('APPROVED',{reason_code:'REQUEST_AND_SCOPE_VERIFIED'})).response.status,200);
  const plan=await post(`/api/v1/privacy-operations/requests/${requestId}/fulfilment-plans`,operatorAuth,'plan');
  const planId=plan.payload.data.id;
  assert.equal((await post(`/api/v1/privacy-operations/fulfilment-plans/${planId}/impact-assessment`,operatorAuth,'impact')).response.status,200);
  const privacyIssued=await post('/api/v1/local-demo/privacy-approver/privacy/session','','privacy-session');
  const securityIssued=await post('/api/v1/local-demo/privacy-approver/security/session','','security-session');
  const privacyAuth=`Bearer ${privacyIssued.payload.data.access_token}`;
  const securityAuth=`Bearer ${securityIssued.payload.data.access_token}`;
  assert.equal((await post(`/api/v1/privacy-operations/fulfilment-plans/${planId}/approvals`,privacyAuth,'privacy-approval',{decision:'APPROVE',reason_code:'PRIVACY_SCOPE_VERIFIED'})).response.status,200);
  assert.equal((await post(`/api/v1/privacy-operations/fulfilment-plans/${planId}/approvals`,securityAuth,'security-approval',{decision:'APPROVE',reason_code:'SECURITY_SCOPE_VERIFIED'})).payload.data.status,'DUAL_APPROVED');
  const sealed=await post(`/api/v1/privacy-operations/fulfilment-plans/${planId}/package-manifests`,operatorAuth,'seal');
  const manifestId=sealed.payload.data.id;
  assert.equal((await post(`/api/v1/privacy-operations/package-manifests/${manifestId}/recovery-checkpoints`,operatorAuth,'checkpoint')).response.status,201);
  const readiness=await post(`/api/v1/privacy-operations/package-manifests/${manifestId}/execution-readiness-reviews`,securityAuth,'readiness');
  const executionHandoff=await post(`/api/v1/privacy-operations/execution-readiness-reviews/${readiness.payload.data.id}/handoff-packets`,securityAuth,'execution-handoff');
  const validation=await post(`/api/v1/privacy-operations/execution-handoff-packets/${executionHandoff.payload.data.id}/evidence-validation-contracts`,securityAuth,'validation');
  const adapter=await post(`/api/v1/privacy-operations/evidence-validation-contracts/${validation.payload.data.id}/intake-adapter-contracts`,securityAuth,'adapter');
  const acceptance=await post(`/api/v1/privacy-operations/intake-adapter-contracts/${adapter.payload.data.id}/connection-acceptance-packets`,securityAuth,'acceptance');
  const queue=await post(`/api/v1/privacy-operations/connection-acceptance-packets/${acceptance.payload.data.id}/configuration-evidence-queue-contracts`,securityAuth,'queue');
  const envelope=await post(`/api/v1/privacy-operations/configuration-evidence-queue-contracts/${queue.payload.data.id}/submission-envelope-contracts`,securityAuth,'envelope');
  const governance=await post(`/api/v1/privacy-operations/submission-envelope-contracts/${envelope.payload.data.id}/reference-scheme-governance-contracts`,securityAuth,'governance');
  const targetValidation=await post(`/api/v1/privacy-operations/reference-scheme-governance-contracts/${governance.payload.data.id}/reference-target-validation-contracts`,securityAuth,'target-validation');
  const proofHandoff=await post(`/api/v1/privacy-operations/reference-target-validation-contracts/${targetValidation.payload.data.id}/reference-proof-handoff-contracts`,securityAuth,'proof-handoff');
  const proofIntake=await post(`/api/v1/privacy-operations/reference-proof-handoff-contracts/${proofHandoff.payload.data.id}/reference-proof-intake-contracts`,securityAuth,'proof-intake');
  assert.equal(proofIntake.response.status,201);
  const proofIntakeId=proofIntake.payload.data.id;

  const operatorDenied=await post(`/api/v1/privacy-operations/reference-proof-intake-contracts/${proofIntakeId}/quarantine-readiness-contracts`,operatorAuth,'operator-denied');
  assert.equal(operatorDenied.response.status,403);
  const first=await post(`/api/v1/privacy-operations/reference-proof-intake-contracts/${proofIntakeId}/quarantine-readiness-contracts`,securityAuth,'readiness-1');
  assert.equal(first.response.status,201);
  assert.equal(first.payload.data.status,'QUARANTINE_READINESS_POLICY_ONLY_EXTERNAL_CONTROLS_MISSING');
  assert.equal(first.payload.data.revision,1);
  assert.equal(hashCanonical(first.payload.data.contract_manifest),first.payload.data.contract_sha256);
  assert.equal(first.payload.data.contract_manifest.storage_security_controls.length,8);
  assert.equal(first.payload.data.contract_manifest.content_inspection_stages.length,8);
  assert.equal(first.payload.data.contract_manifest.content_rejection_codes.length,12);
  assert.equal(first.payload.data.contract_manifest.retention_lifecycle_events.length,7);
  assert.equal(first.payload.data.contract_manifest.audit_required_fields.length,10);
  assert.equal(first.payload.data.contract_manifest.allowed_content_types.length,0);
  assert.equal(first.payload.data.requirements.length,6);
  assert.equal(first.payload.data.requirements.every((item)=>item.allowed_content_types.length===0&&item.storage_status==='MISSING_EXTERNAL'&&item.scanner_status==='MISSING_EXTERNAL'),true);
  assert.equal(first.payload.data.requirements.every((item)=>item.encryption_at_rest_required&&item.deny_public_access_required&&item.object_lock_required&&item.malware_scan_required),true);
  assert.equal(first.payload.data.requirements.every((item)=>item.maximum_object_bytes===null&&item.storage_namespace_reference===null&&item.object_reference===null&&item.scan_result_reference===null),true);
  assert.equal(first.payload.data.requirements.every((item)=>!item.storage_write_allowed&&!item.content_inspection_execution_allowed&&!item.malware_scan_execution_allowed&&!item.deletion_execution_allowed&&!item.audit_event_write_allowed&&!item.quarantine_release_allowed),true);
  assert.equal(first.payload.data.boundary.proof_upload_enabled,false);
  assert.equal(first.payload.data.boundary.quarantine_storage_write_enabled,false);
  assert.equal(first.payload.data.boundary.malware_scan_execution_enabled,false);
  assert.equal(first.payload.data.quarantine_storage_authorized,false);
  assert.equal(first.payload.data.inspection_execution_authorized,false);
  assert.equal(first.payload.data.network_connection_authorized,false);
  assert.equal(first.payload.data.execution_authorized,false);

  const second=await post(`/api/v1/privacy-operations/reference-proof-intake-contracts/${proofIntakeId}/quarantine-readiness-contracts`,securityAuth,'readiness-2');
  assert.equal(second.response.status,201);
  assert.equal(second.payload.data.revision,2);
  assert.equal(second.payload.data.predecessor_contract_id,first.payload.data.id);
  const newerIntake=await post(`/api/v1/privacy-operations/reference-proof-handoff-contracts/${proofHandoff.payload.data.id}/reference-proof-intake-contracts`,securityAuth,'newer-intake');
  assert.equal(newerIntake.response.status,201);
  const staleReadiness=await post(`/api/v1/privacy-operations/reference-proof-intake-contracts/${proofIntakeId}/quarantine-readiness-contracts`,securityAuth,'stale-readiness');
  assert.equal(staleReadiness.response.status,409);
  assert.equal(staleReadiness.payload.error.code,'QUARANTINE_READINESS_INTAKE_SUPERSEDED');

  const operatorRead=await fetch(`${baseUrl}/api/v1/privacy-operations/quarantine-readiness-contracts/${second.payload.data.id}`,{headers:{authorization:operatorAuth}});
  assert.equal(operatorRead.status,200);
  const studentDenied=await fetch(`${baseUrl}/api/v1/privacy-operations/quarantine-readiness-contracts/${second.payload.data.id}`,{headers:{authorization:studentAuth}});
  assert.equal(studentDenied.status,403);
  assert.equal((await post(`/api/v1/privacy-operations/quarantine-readiness-contracts/${second.payload.data.id}/uploads`,securityAuth,'unsupported-upload')).response.status,404);
  assert.equal((await post(`/api/v1/privacy-operations/quarantine-readiness-contracts/${second.payload.data.id}/scans`,securityAuth,'unsupported-scan')).response.status,404);
  assert.equal((await post(`/api/v1/privacy-operations/quarantine-readiness-contracts/${second.payload.data.id}/retention`,securityAuth,'unsupported-retention')).response.status,404);
  assert.equal((await post(`/api/v1/privacy-operations/quarantine-readiness-contracts/${second.payload.data.id}/deletions`,securityAuth,'unsupported-deletion')).response.status,404);
  assert.equal((await post(`/api/v1/privacy-operations/quarantine-readiness-contracts/${second.payload.data.id}/release`,securityAuth,'unsupported-release')).response.status,404);
  const completion=await transition('COMPLETED',{reason_code:'QUARANTINE_POLICY_PRESENT',evidence_reference:'LOCAL-EVIDENCE/no-execution-phase41',evidence_sha256:'5'.repeat(64)});
  assert.equal(completion.response.status,409);
  assert.equal(completion.payload.error.code,'PRIVACY_FULFILMENT_EXECUTOR_DISABLED');
});
