import crypto from 'node:crypto';import fs from 'node:fs';import {EXPANSION_PLAN_CONTROLS,createSyntheticAcceptedPhase60,evaluateExpansionPlan,hashExpansionPlanSource,inspectExpansionPlanRegister} from '../../developer/src/agent/tutor-limited-production-expansion-plan.mjs';
const sourcePath='docs/productization/evidence/PHASE_60_LIMITED_PRODUCTION_EXPANSION_DECISION_REGISTER.json',planPath='docs/productization/evidence/PHASE_61_LIMITED_PRODUCTION_EXPANSION_PLAN_REGISTER.json',contractPath='developer/contracts/ai-tutor-limited-production-expansion-plan-v1.json',outputPath='docs/productization/evidence/PHASE_61_AI_TUTOR_LIMITED_PRODUCTION_EXPANSION_PLAN_QA.json',sourceBytes=fs.readFileSync(sourcePath),planBytes=fs.readFileSync(planPath),contractBytes=fs.readFileSync(contractPath),source=JSON.parse(sourceBytes),planRegister=JSON.parse(planBytes),sourceHash=crypto.createHash('sha256').update(sourceBytes).digest('hex'),clone=(v)=>JSON.parse(JSON.stringify(v)),scenarios=[],record=(id,passed,observed)=>scenarios.push({id,passed,observed});function pair(){const acceptedSource=createSyntheticAcceptedPhase60(source),plan=clone(planRegister),hash=hashExpansionPlanSource(acceptedSource);plan.source_decision.register_sha256=hash;return {acceptedSource,plan,hash};}function verify(plan){plan.control_records=EXPANSION_PLAN_CONTROLS.map((id,n)=>({control_id:id,status:'VERIFIED',evidence_reference:`SYNTHETIC-${n+1}`,verified_at:'2026-08-16T10:10:00+09:00'}));return plan;}function window(plan){plan.execution_window={status:'APPROVED',window_reference:'SYNTHETIC-WINDOW',starts_at:'2026-08-16T10:30:00+09:00',ends_at:'2026-08-16T11:30:00+09:00',approval_inferred:false};return plan;}
{const v=evaluateExpansionPlan({sourceDecisionRegister:source,planRegister,expectedSourceHash:sourceHash});record('current-plan-blocked',v.status==='BLOCKED_EXTERNAL'&&v.controls_verified===0,{status:v.status});}
{const p=pair(),v=evaluateExpansionPlan({sourceDecisionRegister:p.acceptedSource,planRegister:p.plan,expectedSourceHash:p.hash});record('accepted-source-awaits-controls',v.status==='EXPANSION_PLAN_INCOMPLETE',{status:v.status});}
{const f=inspectExpansionPlanRegister(planRegister,{expectedSourceHash:sourceHash});record('eight-locale-sixty-four-request-plan',f.length===0&&planRegister.plan_slots.length===8&&planRegister.plan_slots.reduce((s,i)=>s+i.maximum_requests,0)===64,{failures:f});}
{const p=pair();p.plan.plan_slots.pop();p.plan.plan_slots[1].locale='ko';p.plan.limits.maximum_requests=65;const f=inspectExpansionPlanRegister(p.plan,{expectedSourceHash:p.hash});record('plan-expansion-rejected',['PLAN_SLOT_COUNT_MISMATCH','DUPLICATE_SLOT_LOCALE','LIMIT_MISMATCH:maximum_requests'].every((i)=>f.includes(i)),{failures:f});}
{const p=pair();window(verify(p.plan));const v=evaluateExpansionPlan({sourceDecisionRegister:p.acceptedSource,planRegister:p.plan,expectedSourceHash:p.hash});record('ready-for-review',v.status==='READY_FOR_EXPANSION_PLAN_REVIEW',{status:v.status});}
{const p=pair();window(verify(p.plan));p.plan.review={status:'APPROVED',review_reference:'SYNTHETIC-PO',reviewed_at:'2026-08-16T10:20:00+09:00',approval_inferred:false};const v=evaluateExpansionPlan({sourceDecisionRegister:p.acceptedSource,planRegister:p.plan,expectedSourceHash:p.hash});record('approval-non-dispatching-only',v.status==='EXPANSION_PLAN_ACCEPTED_FOR_EXECUTION_HANDOFF'&&!v.execution_authorized&&!v.dispatch_allowed,{status:v.status});}
{const p=pair();window(verify(p.plan));p.plan.control_records[5]={...p.plan.control_records[5],status:'REJECTED',evidence_reference:'RAW-STORAGE-FAIL'};const v=evaluateExpansionPlan({sourceDecisionRegister:p.acceptedSource,planRegister:p.plan,expectedSourceHash:p.hash});record('rejection-keeps-flag-off',v.status==='EXPANSION_PLAN_REJECTED'&&v.recommendation==='KEEP_FEATURE_FLAG_OFF',{status:v.status});}
{const p=pair();p.plan.response_text='raw';p.plan.secret_reference='sk-exampleSecretMaterial123456';p.plan.plan_executed=true;p.plan.execution_window={status:'APPROVED',window_reference:'WINDOW',starts_at:'2026-08-16T10:00:00+09:00',ends_at:'2026-08-16T11:01:00+09:00',approval_inferred:false};const f=inspectExpansionPlanRegister(p.plan,{expectedSourceHash:'a'.repeat(64)});record('raw-secret-drift-false-execution-overlong-window-rejected',['FORBIDDEN_CONTENT_KEY:response_text','SECRET_MATERIAL_DETECTED','SOURCE_HASH_MISMATCH','PLAN_EXECUTED_MUST_REMAIN_FALSE','EXECUTION_WINDOW_EVIDENCE_REQUIRED'].every((i)=>f.includes(i)),{failures:f});}
const passed=scenarios.filter((i)=>i.passed).length,current=evaluateExpansionPlan({sourceDecisionRegister:source,planRegister,expectedSourceHash:sourceHash}),evidence={schema_version:'1.0.0',phase:61,generated_at:new Date().toISOString(),status:passed===scenarios.length&&current.status==='BLOCKED_EXTERNAL'?'AUTO_QA_PASS_LOCAL_LIMITED_PRODUCTION_EXPANSION_PLAN_BLOCKED_EXTERNAL':'FAIL',current_plan:current,summary:{scenarios:scenarios.length,passed,failed:scenarios.length-passed},scenarios,contract_sha256:crypto.createHash('sha256').update(contractBytes).digest('hex'),source_decision_register_sha256:sourceHash,plan_register_sha256:crypto.createHash('sha256').update(planBytes).digest('hex'),external_actions:{api_key_accessed:false,plan_executed:false,dispatch_performed:false,provider_live_tested:false,feature_flag_changed:false,student_traffic:false,public_traffic:false,production_promotion:false},next_authorized_action:'WAIT_FOR_ACCEPTED_PHASE60_AND_FOURTEEN_VERIFIED_PLAN_CONTROLS'};fs.writeFileSync(outputPath,`${JSON.stringify(evidence,null,2)}\n`);if(evidence.status==='FAIL'){console.error('PHASE61_LIMITED_PRODUCTION_EXPANSION_PLAN_FAIL');scenarios.filter((i)=>!i.passed).forEach((i)=>console.error(i.id));process.exit(1);}console.log('PHASE61_LIMITED_PRODUCTION_EXPANSION_PLAN_PASS');console.log(`local_scenarios=${passed}/${scenarios.length}`);console.log('plan_slots=8/8');console.log('controls_verified=0/14');console.log('plan_executed=false');
